# Code generated by eventgen v0.1.0. DO NOT EDIT.
# Source: contracts/events/_registry.yaml
# Re-generate: make eventgen
"""Event-type name constants — the Python half of the event-name contract.

Import these instead of writing the literal::

    from loreweave_events import EVENT_GLOSSARY_ENTITY_UPDATED

    dispatcher.register(EVENT_GLOSSARY_ENTITY_UPDATED, handle_entity_updated)

WHY THIS MATTERS MORE IN PYTHON THAN IN GO
------------------------------------------
Go gives you a compile error when a constant disappears. Python gives you an ImportError at
STARTUP — which is still enormously better than the alternative this replaces. A
hand-written string literal for an event that no longer exists is valid Python forever: the
dispatcher registers a handler under a name nothing emits, every test that mocks the
dispatcher still passes, and the only symptom is that the handler silently never runs.

That is not hypothetical here. It is recorded as D-GLOSSARY-EVENTS-NO-SOT: seven event
names owned by glossary-service and hand-mirrored by five consumers across four services,
with nothing relating the copies.
"""

EVENT_ADMIN_CANON_OVERRIDE_COMPENSATING = "admin.canon.override.compensating"
EVENT_ADMIN_CANON_OVERRIDE_CONSENTED = "admin.canon.override.consented"
EVENT_ADMIN_CANON_OVERRIDE_REQUESTED = "admin.canon.override.requested"
EVENT_ADMIN_CANON_OVERRIDE_VETOED = "admin.canon.override.vetoed"
EVENT_CANON_CHANGE_RECORDED = "canon.change.recorded"
EVENT_CANON_ENTRY_CREATED = "canon.entry.created"
EVENT_CANON_ENTRY_DECANONIZED = "canon.entry.decanonized"
EVENT_CANON_ENTRY_PROMOTED = "canon.entry.promoted"
EVENT_CANON_ENTRY_UPDATED = "canon.entry.updated"
EVENT_GLOSSARY_ENTITY_DELETED = "glossary.entity_deleted"
EVENT_GLOSSARY_ENTITY_MERGED = "glossary.entity_merged"
EVENT_GLOSSARY_ENTITY_PURGED = "glossary.entity_purged"
EVENT_GLOSSARY_ENTITY_RESTORED = "glossary.entity_restored"
EVENT_GLOSSARY_ENTITY_STATUS_CHANGED = "glossary.entity_status_changed"
EVENT_GLOSSARY_ENTITY_UPDATED = "glossary.entity_updated"
EVENT_GLOSSARY_NAME_CONFIRMED = "glossary.name_confirmed"
EVENT_NPC_SAID = "npc.said"
EVENT_REALITY_CREATED = "reality.created"
EVENT_RULESET_EPOCH_ACTIVATED = "ruleset.epoch_activated"
EVENT_WORLD_TICK = "world.tick"
EVENT_XREALITY_CANON_PROMOTED = "xreality.canon.promoted"
EVENT_XREALITY_USER_ERASED = "xreality.user.erased"

__all__ = [
    "EVENT_ADMIN_CANON_OVERRIDE_COMPENSATING",
    "EVENT_ADMIN_CANON_OVERRIDE_CONSENTED",
    "EVENT_ADMIN_CANON_OVERRIDE_REQUESTED",
    "EVENT_ADMIN_CANON_OVERRIDE_VETOED",
    "EVENT_CANON_CHANGE_RECORDED",
    "EVENT_CANON_ENTRY_CREATED",
    "EVENT_CANON_ENTRY_DECANONIZED",
    "EVENT_CANON_ENTRY_PROMOTED",
    "EVENT_CANON_ENTRY_UPDATED",
    "EVENT_GLOSSARY_ENTITY_DELETED",
    "EVENT_GLOSSARY_ENTITY_MERGED",
    "EVENT_GLOSSARY_ENTITY_PURGED",
    "EVENT_GLOSSARY_ENTITY_RESTORED",
    "EVENT_GLOSSARY_ENTITY_STATUS_CHANGED",
    "EVENT_GLOSSARY_ENTITY_UPDATED",
    "EVENT_GLOSSARY_NAME_CONFIRMED",
    "EVENT_NPC_SAID",
    "EVENT_REALITY_CREATED",
    "EVENT_RULESET_EPOCH_ACTIVATED",
    "EVENT_WORLD_TICK",
    "EVENT_XREALITY_CANON_PROMOTED",
    "EVENT_XREALITY_USER_ERASED",
]
