#!/usr/bin/env python3
"""Generate `docker-compose.isolated.yml` — a second, fully separate local stack.

WHY THIS EXISTS
---------------
Two branches were working the same checkout against the same Compose stack. `docker compose
build glossary-service` on either branch overwrites the SAME image tag, `up` replaces the
SAME container, and both write the SAME databases. Whoever ran last won, silently, and the
loser's live smoke measured the other branch's code.

The fix is a second Compose PROJECT. Compose namespaces containers, networks, volumes and
image tags by project name, so `-p lw-iso` already gives us our own everything — with one
exception it cannot solve by itself: **published host ports are absolute**, so a second
project binding 5555 just fails to start.

This generates the port remapping. Isolated port = base port + 20000, for all 47 published
ports across 42 services.

    5555  -> 25555   postgres
    7688  -> 27688   neo4j bolt
    8211  -> 28211   glossary-service
    8216  -> 28216   knowledge-service

Why +20000 and not the obvious +10000: rabbitmq's management UI is already published on
15795, and 5795 + 10000 lands exactly on it. Every base port is below 20000, so a 20000
offset cannot collide with the base stack, and the highest result (15795 -> 35795) is well
inside the port range.

WHY A GENERATED OVERRIDE AND NOT A COPY OF THE COMPOSE FILE
------------------------------------------------------------
A copied 2172-line compose file is a second source of truth. It would agree with the
original on the day it was made and drift from that day on — a service added to one, an
env var changed in the other — and nothing would notice. `CLAUDE.md` states the rule this
repo lives by: *one home, one name; guidance that is duplicated goes stale in one copy and
then actively misleads.* The same applies to infrastructure.

So the isolated stack IS the base stack, plus a mechanically-derived port shift. Change a
service in `docker-compose.yml` and both stacks get it. Add a published port and
`--check` reds until this file is regenerated.

⚠️ `ports:` carries the `!override` tag deliberately. Compose CONCATENATES multi-value keys
like `ports` across files, so a plain override would publish 5555 AND 25555 — the isolated
stack would fight the base one for the very port this file exists to move, and the error
would look like "the other stack is broken" rather than "the merge appended".

    python infra/gen-isolated-compose.py            # regenerate
    python infra/gen-isolated-compose.py --check    # red if the base grew a port
"""
from __future__ import annotations

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "docker-compose.yml")
OUT = os.path.join(HERE, "docker-compose.isolated.yml")

PORT_OFFSET = 20000

_SERVICE = re.compile(r"^  ([a-z0-9_-]+):\s*$")
_PORTS_KEY = re.compile(r"^    ports:\s*$")
_PORT_ENTRY = re.compile(r'^\s*-\s*"(\d+):(\d+)"\s*(#.*)?$')


def collect(path: str) -> list[tuple[str, int, int, str]]:
    """(service, host_port, container_port, trailing comment) for every published port."""
    rows: list[tuple[str, int, int, str]] = []
    service = None
    in_ports = False
    for line in io.open(path, encoding="utf-8").read().splitlines():
        matched = _SERVICE.match(line)
        if matched:
            service = matched.group(1)
            in_ports = False
            continue
        if _PORTS_KEY.match(line):
            in_ports = True
            continue
        if not in_ports:
            continue
        # Any key at the service's own indent ends the list.
        if line.strip() and not line.startswith("      "):
            in_ports = False
            continue
        entry = _PORT_ENTRY.match(line)
        if entry:
            rows.append((service, int(entry.group(1)), int(entry.group(2)),
                         (entry.group(3) or "").strip()))
        elif line.strip().startswith("- "):
            # A shape this generator does not understand (long syntax, a bind address, a
            # range). Refusing is the point: silently skipping it would leave the isolated
            # stack publishing the BASE port and colliding, and the failure would surface
            # as an unrelated "address already in use".
            raise SystemExit(
                f"gen-isolated-compose: unhandled ports entry in `{service}`:\n"
                f"    {line.strip()}\n"
                "Teach this script the shape rather than dropping it — an unremapped "
                "port is a collision with the base stack."
            )
    return rows


HEADER = f"""\
# ⚠️ GENERATED by `python infra/gen-isolated-compose.py` — DO NOT EDIT BY HAND.
#
# The port half of the ISOLATED local stack: the same services as docker-compose.yml,
# published on host ports shifted by +{PORT_OFFSET} so a second Compose project can run
# beside the base one without fighting it for a socket.
#
# This file is only half of the isolation. The other half is the project NAME, which is
# what actually separates containers, networks, volumes and image tags:
#
#     docker compose -p lw-iso -f docker-compose.yml -f docker-compose.isolated.yml up -d
#
# Use `infra/iso.sh` (or `infra/iso.ps1`) rather than typing that — forgetting `-p lw-iso`
# runs the ISOLATED PORTS against the SHARED containers and volumes, which is worse than
# either stack alone and looks like data corruption.
#
# `!override` replaces the base `ports:` list instead of appending to it. Without the tag
# Compose concatenates the two, the isolated stack tries to bind the base port as well,
# and the collision reads as "the other stack is broken".
#
# Regenerate after adding a published port to docker-compose.yml;
# `python infra/gen-isolated-compose.py --check` reds if you forget.

services:
"""


def render(rows: list[tuple[str, int, int, str]]) -> str:
    out = [HEADER]
    by_service: dict[str, list[tuple[int, int, str]]] = {}
    for service, host, container, comment in rows:
        by_service.setdefault(service, []).append((host, container, comment))
    for service in sorted(by_service):
        out.append(f"  {service}:\n    ports: !override\n")
        for host, container, comment in by_service[service]:
            shifted = host + PORT_OFFSET
            # The base file's comments spell out host URLs ("host: bolt://localhost:7688").
            # Carried over verbatim they would name the OTHER stack's port, in the one file
            # whose entire job is that the port is different.
            comment = re.sub(rf"\b{host}\b", str(shifted), comment)
            tail = f"   {comment}" if comment else ""
            out.append(f'      - "{shifted}:{container}"{tail}'.rstrip() + "\n")
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail if the generated file is stale")
    args = parser.parse_args()

    rows = collect(BASE)
    rendered = render(rows)

    # A shifted port must never land on a port the BASE stack publishes, or the two stacks
    # collide on a port that looks isolated.
    base_ports = {host for _s, host, _c, _k in rows}
    for _service, host, _container, _comment in rows:
        if host + PORT_OFFSET in base_ports:
            print(f"gen-isolated-compose: FAIL — {host} + {PORT_OFFSET} = "
                  f"{host + PORT_OFFSET}, which the base stack already publishes. "
                  "Pick a different offset.")
            return 1

    if args.check:
        current = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != rendered:
            print("gen-isolated-compose: FAIL — docker-compose.isolated.yml is STALE.\n"
                  "  docker-compose.yml published ports have changed. Regenerate:\n"
                  "      python infra/gen-isolated-compose.py\n"
                  "  A stale override leaves the new service publishing its BASE port, so "
                  "the isolated\n  stack quietly fights the shared one for it.")
            return 1
        print(f"gen-isolated-compose: OK — {len(rows)} port(s) across "
              f"{len({r[0] for r in rows})} service(s), offset +{PORT_OFFSET}, in sync")
        return 0

    io.open(OUT, "w", encoding="utf-8", newline="\n").write(rendered)
    print(f"gen-isolated-compose: wrote {os.path.relpath(OUT)} — {len(rows)} port(s) "
          f"across {len({r[0] for r in rows})} service(s), offset +{PORT_OFFSET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
