-- 0022_actors — the per-reality actor registry: `S-9`'s missing conversion site.
--
-- WHY THIS EXISTS
-- ---------------
-- `migrations/meta/034_actor_control_binding` records WHO drives WHICH actor,
-- and types the actor as a UUID. The island types an actor as
-- `sim-core::EntityId(pub u64)`. The actor-hub round measured the gap and
-- deferred it:
--
--     S-9 · `EntityId(u64)` is "identity within a reality"; `GoneState` is keyed
--           by `EntityRef { uuid, aggregate_type, reality_id }`; ZERO CONVERSION
--           SITES EXIST.  Trigger: platform, when the hub first meets it.
--
-- The hub has met it: a resolver that answers "which actor does this user
-- drive?" has to hand the island something it can act on, and there was nothing
-- to convert through.
--
-- Worse, the UUID pointed at nothing. `0017_drop_pc_npc_projections` removed
-- `pc_projection` / `npc_projection` and their five siblings — correctly, they
-- had no producer — and the platform's only DURABLE actor identity went with
-- them. Measured against a database carrying the full chain: no `pc_*`/`npc_*`
-- table survives, and the only actors in the running system are `EntityId(1)`,
-- `(2)` and `(3)`, hardcoded in `bin/spine.rs` and living in island memory.
--
-- THIS IS NOT A FIFTH SPELLING (SF-6)
-- -----------------------------------
-- `0021_turn_slot` refused to mint an `ActorId` because four spellings of "who
-- is acting" already exist, and named its reversal trigger: *"a single
-- actor-identity type being adopted repo-wide"*.
--
-- This table mints NO new vocabulary. It is the MAPPING between two spellings
-- that already exist — the platform's `actor_id UUID` and the island's
-- `EntityId(u64)` — written down in the one place both tiers can reach. A third
-- name for the same thing is what `SF-6` forbids, and this is the opposite: the
-- conversion site whose absence `S-9` recorded.
--
-- It does NOT perform the repo-wide adoption. `GoneState`'s `EntityRef`,
-- `pii_sdk` and the meta audit tables are untouched; that work is tracked as
-- `PC-SF6-REVERSAL`.
--
-- WHY THE REGISTRY ALLOCATES `entity_id`
-- --------------------------------------
-- `GENERATED BY DEFAULT AS IDENTITY`, not a column the caller must fill. If the
-- island kept allocating and the table merely recorded, the two would be a
-- second SSOT for the same number and would drift the first time an actor was
-- created twice — which is how `pc_projection` came to disagree with nothing at
-- all. `BY DEFAULT` rather than `ALWAYS` so an explicit id can still be supplied
-- when adopting entities that already exist (the spine's hardcoded 1..3).
--
-- Per-reality, so the sequence is per-reality, which is exactly the scope
-- `sim-core` gives `EntityId`: *"identity within a reality"*.

CREATE TABLE IF NOT EXISTS actors (
    -- Carried even though the database is already per-reality, matching
    -- `events` and `channels`. The rebuild path reads rows out of context.
    reality_id  UUID    NOT NULL,

    -- The PLATFORM's actor identity — what `actor_control_binding.actor_id`
    -- points at, and what a lifecycle operation keyed by `EntityRef` would use.
    actor_id    UUID    NOT NULL,

    -- The ISLAND's actor identity. The whole reason for this table.
    entity_id   BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (reality_id, actor_id),

    -- The mapping is a BIJECTION or it is not a mapping. Without this, two
    -- actor uuids could name one island entity and a resolver would have no
    -- answer to "which actor is this" — the confused-deputy problem one tier
    -- down from the one `034` prevents.
    CONSTRAINT actors_entity_id_unique UNIQUE (reality_id, entity_id)
);

-- The resolver's query: binding gives an `actor_id`, this answers with the
-- `entity_id` the island acts on. Served by the PK's prefix already; named here
-- because the reverse direction is the one the rebuild path needs.
CREATE INDEX IF NOT EXISTS actors_by_entity_id
    ON actors (reality_id, entity_id);
