-- 0023_actors_entity_id_nonneg — the CHECK `0022` did not need and then did.
--
-- WHY THIS EXISTS
-- ---------------
-- `actors.entity_id` is `BIGINT` and `sim_core::EntityId` is a `u64`. `0022`
-- put no `CHECK` on the column and gave a reason that was true at the time: the
-- identity sequence only ever allocates positives.
--
-- But `GENERATED BY DEFAULT` exists precisely so an explicit value CAN be
-- supplied, and `actor_registry::adopt_actor` supplies one straight from an
-- operator's `--entity-id`. So `admin reality create-actor --entity-id -1`
-- succeeded, the grant that followed succeeded, and the actor was then
-- permanently unable to act: `commit_service::subject` refuses a negative with
-- `NotAnEntityId` at turn time, correctly, because `-1 as u64` is `u64::MAX` —
-- a well-typed number naming an entity that does not exist. A character that
-- could be created and granted and never used, with nothing on the path saying
-- so. Found 2026-08-21 by the `E1` audit.
--
-- WHY A CONSTRAINT WHEN THE CODE ALREADY REFUSES IT
-- --------------------------------------------------
-- `actor_registry::checked_island_id` guards both edges — the write
-- (`adopt_actor`) and the read (`actor_control_flow::resolve_subject`) — and
-- both are bitten. That closes the paths that exist. It does not close the path
-- somebody adds next month: a new writer that reaches `actors` without the
-- helper is unguarded, and nothing would go red. `NV-3` names that shape —
-- an enumerated set of call sites is default-uncovered.
--
-- The column is the only place the rule cannot be routed around.
--
-- `NOT VALID` IS DELIBERATELY NOT USED
-- ------------------------------------
-- A `NOT VALID` constraint would skip the scan and let an existing bad row
-- survive while claiming the invariant. There should be no such row — the code
-- guard has been in place since the same day this was found — and if one
-- exists, this migration failing IS the right outcome: it says the invariant
-- was already broken, which is the thing worth knowing.

-- IDEMPOTENT, and the first version was not.
--
-- Re-provisioning a completed reality RE-APPLIES the migration set — that is
-- the retry-safe behaviour `provisioner_reentry_live` exists to hold — and
-- Postgres has no `ADD CONSTRAINT IF NOT EXISTS`, so a bare `ALTER TABLE ... ADD
-- CONSTRAINT` fails the second time with *"constraint already exists"*. Every
-- other file in this directory is idempotent by construction (`CREATE TABLE IF
-- NOT EXISTS`, `CREATE INDEX IF NOT EXISTS`); a constraint needs the guard
-- written out. Caught by that suite on the first full run after this file
-- landed, which is the whole reason it is a live suite.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'actors_entity_id_nonneg'
          AND conrelid = 'actors'::regclass
    ) THEN
        ALTER TABLE actors
            ADD CONSTRAINT actors_entity_id_nonneg CHECK (entity_id >= 0);
    END IF;
END $$;
