-- 0028_portal.up.sql
--
-- THE CONNECTIVE RELATION. `0019_channels` ships CONTAINMENT -- a strict acyclic
-- tree where `parent` is the only edge. `parent` cannot express a door.
--
-- `SPG-A18` (`SDF-R3`, applied to doc 36 §3.2 in the same commit as this file)
-- states the rule: containment and connectivity are TWO relations over one node
-- set, and a portal is a first-class object with its own identity.
--
-- Both `0024_map_layout` and `0026_place` deliberately left a connections column
-- out and said why: shipping edges before this amendment landed would have
-- decided the connective-adjacency relation BY ACCIDENT, twice. This is the
-- decision they were waiting for.
--
-- ONE RECORD, TWO ENDS -- AND A ONE-SIDED LINK IS NOT REPRESENTABLE.
--
--   Bethesda's `XTEL` stores a destination reference and a transform and NEVER a
--   destination cell id, so a door pair is two independent one-way records that
--   nothing keeps in step. `R-59`: "which is exactly why one-sided door links are
--   a classic mod bug." A schema of two directed rows would reproduce it exactly.
--   One row with two ends makes the bug UNREPRESENTABLE rather than validated,
--   which is the same trade `0025`'s sum-type CHECK makes for locations.
--
-- NO WORLD COORDINATES. An end is `(node, anchor_x, anchor_y)` and the anchor is
-- PARENT-RELATIVE in `MAP_001`'s 0..1000 frame, exactly like `map_layout`. With
-- `SPG-A5` that means a `Domain` with mobility can MOVE and every portal into it
-- stays valid with zero fixups -- a ship sails and its gangway still lands where
-- it should. An absolute position would turn every portal into a repair job.
--
-- WHAT IS DEFERRED:
--   `gate: Option<LayerId>` -- a locked door is a LAYER on the portal, and the
--       layer registry (`T4`) is not built. A column pointing at a registry that
--       does not exist would be a dangling reference with a type.
--   turn restrictions on `(in_portal, out_portal)` inside a `Passage` (`R-21`)
--       -- they need two portals to exist first, which is this table.

BEGIN;

CREATE TABLE IF NOT EXISTS portal (
    reality_id  UUID    NOT NULL,
    portal_id   BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    -- The two ends. Named `a`/`b` rather than `from`/`to` ON PURPOSE: a portal
    -- is SYMMETRIC, and `from`/`to` would invite exactly the directed reading
    -- that produced the Bethesda defect.
    node_a      BIGINT  NOT NULL,
    anchor_a_x  INTEGER NOT NULL,
    anchor_a_y  INTEGER NOT NULL,

    node_b      BIGINT  NOT NULL,
    anchor_b_x  INTEGER NOT NULL,
    anchor_b_y  INTEGER NOT NULL,

    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (reality_id, portal_id),

    -- `0023`'s lesson, one table over: an identity column is GENERATED BY
    -- DEFAULT, so an explicit value can be supplied, and a negative id would be
    -- creatable and then permanently unresolvable.
    CONSTRAINT portal_id_positive CHECK (portal_id > 0),

    -- Both ends must be real nodes, in THIS reality. RESTRICT rather than
    -- CASCADE, and for the same reason as `0025`: silently deleting the way into
    -- a place because the place on the other side went away is how a world
    -- quietly becomes unreachable. `R-52`'s evacuate-never-delete applies to
    -- ways as much as to occupants.
    CONSTRAINT portal_node_a_fk FOREIGN KEY (reality_id, node_a)
        REFERENCES channels (reality_id, id) ON DELETE RESTRICT,
    CONSTRAINT portal_node_b_fk FOREIGN KEY (reality_id, node_b)
        REFERENCES channels (reality_id, id) ON DELETE RESTRICT,

    -- A portal from a node to itself is not a door, it is a loop with a
    -- description. `PF_001` rejects the same shape at the place tier
    -- (`place.self_referential_connection`).
    CONSTRAINT portal_not_self CHECK (node_a <> node_b),

    -- The same 0..1000 parent-relative frame `map_layout` uses. Repeated rather
    -- than referenced, because a CHECK cannot reach another table -- and an
    -- anchor outside its node's frame is meaningless in exactly the way a
    -- position outside it is.
    CONSTRAINT portal_anchor_a_in_frame
        CHECK (anchor_a_x BETWEEN 0 AND 1000 AND anchor_a_y BETWEEN 0 AND 1000),
    CONSTRAINT portal_anchor_b_in_frame
        CHECK (anchor_b_x BETWEEN 0 AND 1000 AND anchor_b_y BETWEEN 0 AND 1000)
);

-- ONE PORTAL PER UNORDERED PAIR. Two rows for one doorway is the two-one-way-
-- records defect arriving by duplication instead of by schema, so the pair is
-- normalised with LEAST/GREATEST and made unique. This is what stops
-- `(house, street)` and `(street, house)` from both existing.
CREATE UNIQUE INDEX IF NOT EXISTS portal_unordered_pair_uq
    ON portal (reality_id, LEAST(node_a, node_b), GREATEST(node_a, node_b));

-- "Which ways lead out of this node" -- the traversal query, and the one a
-- portal-graph read (`Adjacency::Connective`) walks. Two indexes because a
-- portal is symmetric and either end may be the one asked about.
CREATE INDEX IF NOT EXISTS portal_by_node_a ON portal (reality_id, node_a);
CREATE INDEX IF NOT EXISTS portal_by_node_b ON portal (reality_id, node_b);

COMMIT;
