-- 0030_encounter.up.sql
--
-- `T9` -- THE ENCOUNTER CLOSURE. Doc 41 §5 lists this as one of the two tables
-- the sealed design does not merely LACK but has the WRONG SHAPE for, because
-- doc 36 had only the node.
--
-- `SPG-A19` (`SDF-R4`, applied in this same commit) states the rule: an
-- `Encounter` is not an `Arena`. The Encounter ALWAYS exists during a fight; the
-- Arena node is OPTIONAL, merely a space the Encounter may point at. Foundry VTT
-- is the shipped proof -- its `Combat` document holds `scene` as a FOREIGN KEY,
-- not ownership, and multiple Combats run on one Scene at once.
--
-- ## `carved_arena` IS THE WHOLE BRANCH
--
-- `NULL` is in place; a value is carved. Everything else about the row is
-- identical, which is what turns `SPG-D1`'s hybrid decision into a ONE-LINE
-- BRANCH instead of two code paths. Without the split, in-place combat forces
-- either carving an Arena anyway just to have somewhere to hang state -- which
-- defeats the decision entirely -- or giving every Locale and Domain
-- combat-shaped columns that are NULL 99.9% of the time.
--
-- ## WHY THERE IS AN OPENING-FRAME DIGEST, AND IT IS NOT BOOKKEEPING
--
-- `R-7`: XCOM 2's replay works because a tactical mission is a CLOSED WORLD --
-- a start frame, an append-only chain, and nothing external injecting. An
-- in-place fight in a persistent shared `Locale` is an OPEN world: a wandering
-- NPC, a day/night tick, another party's area effect or a weather change can all
-- perturb it. Under this project's own constraint -- a fight must replay
-- identically from its event log -- `SPG-D1` as written was NOT SATISFIABLE.
--
-- The reframing: IN PLACE means "no separate SPACE". It does not mean "no
-- ISOLATION BOUNDARY". So everything the fight reads is snapshotted at siting
-- into the log's opening frame (about 2.3 KB for a 24x24 terrain slice -- cheap
-- enough that the closed-world property costs nothing), and this column carries
-- that frame's content hash. **The closure exists in BOTH branches**, which is
-- the half `SPG-D1` never addressed.
--
-- ## WHAT THIS TABLE DELIBERATELY DOES NOT HAVE
--
-- Damage, initiative, turn order, action budgets, status stacking, participants'
-- rolls -- `COMB_*`'s, every one. This tier states that a boundary EXISTS, WHERE
-- it sits, and WHAT CROSSES it. What happens inside it is not the map's to
-- design, and a column here would decide it by accident. `participants` is
-- likewise absent: a combatant is a REFERENCE (`R-6`, Foundry), so it belongs in
-- a join owned by the feature that knows what a combatant is.

BEGIN;

CREATE TABLE IF NOT EXISTS encounter (
    reality_id      UUID    NOT NULL,
    encounter_id    BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    -- WHERE the fight is happening. Always present -- a fight is somewhere, in
    -- both branches.
    sited_at_node   BIGINT  NOT NULL,

    -- `SPG-A19`. NULL = in place; a value = an Arena was carved. THE BRANCH.
    carved_arena    BIGINT,

    -- `R-7`'s closure. The content hash of the opening frame snapshotted at
    -- siting -- what makes an in-place fight a closed world despite living in an
    -- open one. `blake3-128`, hex, same convention as `layer_registry.layer_id`.
    opening_frame   TEXT    NOT NULL,

    -- Open until disposal. `R-7` rule 3: nothing outside the closure is mutated
    -- until an atomic commit at disposal, so "is this closure still open" is a
    -- question the schema must be able to answer.
    status          TEXT    NOT NULL DEFAULT 'open',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    disposed_at     TIMESTAMPTZ,

    PRIMARY KEY (reality_id, encounter_id),

    CONSTRAINT encounter_id_positive CHECK (encounter_id > 0),

    CONSTRAINT encounter_opening_frame_is_blake3_128
        CHECK (opening_frame ~ '^[0-9a-f]{32}$'),

    CONSTRAINT encounter_status_closed
        CHECK (status IN ('open', 'disposed')),

    -- Disposal and its timestamp are ONE fact. A disposed closure with no time,
    -- or a time with an open closure, is a row that two readers would answer
    -- differently -- the same shape `0019`'s `dissolved_at` guard refuses.
    CONSTRAINT encounter_disposed_at_iff_disposed CHECK (
        (status = 'disposed' AND disposed_at IS NOT NULL)
        OR (status = 'open' AND disposed_at IS NULL)
    ),

    -- An Arena is a SPACE the encounter points at, never the encounter itself,
    -- so pointing at the node it is already sited in is a confusion rather than
    -- a configuration.
    CONSTRAINT encounter_arena_is_not_the_site
        CHECK (carved_arena IS NULL OR carved_arena <> sited_at_node),

    -- Both node references are real nodes in THIS reality. RESTRICT for the same
    -- reason as `0025` and `0028`: deleting the ground out from under a running
    -- fight is `R-52`'s evacuate-never-delete arriving a third time.
    CONSTRAINT encounter_site_fk FOREIGN KEY (reality_id, sited_at_node)
        REFERENCES channels (reality_id, id) ON DELETE RESTRICT,
    CONSTRAINT encounter_arena_fk FOREIGN KEY (reality_id, carved_arena)
        REFERENCES channels (reality_id, id) ON DELETE RESTRICT
);

-- "What is happening at this node right now" -- the question a scene assembler
-- and a mover both ask, and the reason `R-6` says multiple Combats may share one
-- Scene: this is deliberately NOT unique.
CREATE INDEX IF NOT EXISTS encounter_by_site
    ON encounter (reality_id, sited_at_node) WHERE status = 'open';

COMMIT;
