//! V2 data model — closed-primitive enums for terrain + object semantics.
//!
//! Engine code paths bind here; **adding a variant is a major version bump**.
//! Configurable behavior is encoded as properties on registry entries
//! (see [`crate::types::registry`]) and dispatched at runtime by the
//! relevant engine module.
//!
//! Decision criterion: a variant is a primitive when adding it requires
//! the engine to write a new handler (tick loop, persistent state,
//! lookup table). Configurable behaviors (movement speed, resource yield,
//! climate zone, etc.) are PROPERTIES on existing primitives.
//!
//! See ADR `docs/specs/2026-05-26-data-model-v2-registry-footprint.md` §2.1.

use serde::{Deserialize, Serialize};

/// Engine-level terrain semantics. Every tile resolves to exactly one
/// primitive. Configurable via properties on the corresponding
/// [`crate::types::registry::TerrainKindDef`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TerrainPrimitive {
    /// Walkable substrate. Default for any non-special tile. Configurable
    /// via properties: `movement_speed`, `growth_capacity`, `resource_yield`,
    /// `climate_zone`, `z_level`, etc.
    Land,
    /// Impassable surface; bridge/ford crossings allowed via L1/L2
    /// overlay placement. Future `depth` property reserved for swim split.
    Water,
    /// Impassable rock face; no crossings possible.
    Wall,
    /// Walkable + road render + future movement bonus. Generated by
    /// `RoadPlacer`; bridges are `Path` tiles laid over `Water`.
    Path,
    /// Walkable + damage tick handler (lava, acid, poison fog).
    /// `damage_per_tick` property pins the rate.
    Hazard,
    /// Unrendered; collision treated as wall. Off-map / unknown.
    Void,
}

impl TerrainPrimitive {
    /// Default walkability — engine may override per registry properties
    /// (e.g. `Wall` with `transparent: true` still blocks movement but
    /// passes line-of-sight when LOS engine ships).
    pub fn is_walkable(self) -> bool {
        match self {
            Self::Land | Self::Path | Self::Hazard => true,
            Self::Water | Self::Wall | Self::Void => false,
        }
    }

    /// Whether engine renders this tile at all. `Void` skips render.
    pub fn is_rendered(self) -> bool {
        !matches!(self, Self::Void)
    }
}

/// Engine-level object semantics. Every object kind resolves to one
/// primitive. Configurable via properties on the corresponding
/// [`crate::types::registry::ObjectKindDef`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ObjectPrimitive {
    /// Walkable, no effect, no state. Lantern, sign-only (with
    /// `readable: true` + `text: "..."`), debris.
    Decoration,
    /// Walkable; auto-collect on enter; one-shot consume. Treasure pile,
    /// dropped coin, herb on ground.
    Pickup,
    /// Walkable; manual open; persistent loot state. Chest, barrel.
    /// Crafting stations sit here via `interaction_kind: crafting`.
    Container,
    /// Walkable; drill-down to interior scene (CSC_001). Town,
    /// settlement, dungeon entrance.
    Habitable,
    /// Impassable; stateless. Mountain, tree, rock pillar.
    /// `transparent: true` reserved for future LOS engine.
    Blocker,
    /// Toggleable [`Blocker`]; persistent open/closed state. Gate, hatch.
    /// `locked: true + key_id: "..."` for locked doors.
    Door,
    /// Walkable; fires event on enter (or other condition via
    /// `condition: "proximity_3 | item_held=key | time=midnight"`).
    /// Portal, pressure plate, narrative anchor.
    Trigger,
    /// Walkable; transport mechanic; routes player to destination.
    /// Ferry, mount, cart, teleporter. Distinct from [`Trigger`]:
    /// `Trigger` fires event + done; `Vehicle` may have persistent
    /// state (fuel, durability).
    Vehicle,
    /// Periodic entity generation. Monster nest, spawn point.
    /// `spawn_pool: [..]` + `tick_interval` properties.
    Spawner,
    /// Periodic INVENTORY resource generation (distinct from `Spawner`
    /// which yields ENTITIES). Farm, mine, fishing spot, herb patch.
    /// `resource_yield: { ore: 3, gem: 1 }` + `tick_interval`.
    Producer,
    /// Growing entity — harvestable; may spread; may have age states.
    /// Tree, crop, mushroom patch. Distinct from `Producer` (static
    /// building); `Plant` is the entity itself.
    /// `growth_capacity` + `harvest_yield` + `spread_chance` properties.
    Plant,
}

impl ObjectPrimitive {
    /// Default per-tile walkability for objects of this primitive.
    /// **Read this as "the value used when `walkability_pattern` is
    /// `None`"** — not as a final per-tile decision. Engine composes
    /// this with terrain primitive walkability + per-tile mask (if any).
    pub fn primitive_default_walkable(self) -> bool {
        match self {
            Self::Decoration
            | Self::Pickup
            | Self::Container
            | Self::Habitable
            | Self::Trigger
            | Self::Vehicle
            | Self::Producer => true,
            Self::Blocker | Self::Door | Self::Spawner | Self::Plant => false,
        }
    }

    /// Whether this primitive carries persistent state (loot, lock,
    /// growth-stage, etc.). Engine uses this to size persistence layer
    /// scope per placement.
    pub fn has_persistent_state(self) -> bool {
        matches!(
            self,
            Self::Container
                | Self::Door
                | Self::Vehicle
                | Self::Spawner
                | Self::Producer
                | Self::Plant
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn terrain_primitive_serde_round_trip() {
        for v in [
            TerrainPrimitive::Land,
            TerrainPrimitive::Water,
            TerrainPrimitive::Wall,
            TerrainPrimitive::Path,
            TerrainPrimitive::Hazard,
            TerrainPrimitive::Void,
        ] {
            let json = serde_json::to_string(&v).unwrap();
            let back: TerrainPrimitive = serde_json::from_str(&json).unwrap();
            assert_eq!(v, back, "round-trip {v:?}");
        }
    }

    #[test]
    fn terrain_primitive_wire_tags_are_snake_case() {
        assert_eq!(serde_json::to_string(&TerrainPrimitive::Land).unwrap(), "\"land\"");
        assert_eq!(serde_json::to_string(&TerrainPrimitive::Water).unwrap(), "\"water\"");
        assert_eq!(serde_json::to_string(&TerrainPrimitive::Wall).unwrap(), "\"wall\"");
        assert_eq!(serde_json::to_string(&TerrainPrimitive::Path).unwrap(), "\"path\"");
        assert_eq!(serde_json::to_string(&TerrainPrimitive::Hazard).unwrap(), "\"hazard\"");
        assert_eq!(serde_json::to_string(&TerrainPrimitive::Void).unwrap(), "\"void\"");
    }

    #[test]
    fn terrain_walkability_matches_design() {
        assert!(TerrainPrimitive::Land.is_walkable());
        assert!(TerrainPrimitive::Path.is_walkable());
        assert!(TerrainPrimitive::Hazard.is_walkable()); // walkable but hurts
        assert!(!TerrainPrimitive::Water.is_walkable());
        assert!(!TerrainPrimitive::Wall.is_walkable());
        assert!(!TerrainPrimitive::Void.is_walkable());
    }

    #[test]
    fn terrain_void_is_unrendered() {
        assert!(!TerrainPrimitive::Void.is_rendered());
        assert!(TerrainPrimitive::Land.is_rendered());
        assert!(TerrainPrimitive::Hazard.is_rendered());
    }

    #[test]
    fn object_primitive_serde_round_trip() {
        for v in [
            ObjectPrimitive::Decoration,
            ObjectPrimitive::Pickup,
            ObjectPrimitive::Container,
            ObjectPrimitive::Habitable,
            ObjectPrimitive::Blocker,
            ObjectPrimitive::Door,
            ObjectPrimitive::Trigger,
            ObjectPrimitive::Vehicle,
            ObjectPrimitive::Spawner,
            ObjectPrimitive::Producer,
            ObjectPrimitive::Plant,
        ] {
            let json = serde_json::to_string(&v).unwrap();
            let back: ObjectPrimitive = serde_json::from_str(&json).unwrap();
            assert_eq!(v, back, "round-trip {v:?}");
        }
    }

    #[test]
    fn object_primitive_wire_tags_are_snake_case() {
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Decoration).unwrap(), "\"decoration\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Pickup).unwrap(), "\"pickup\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Container).unwrap(), "\"container\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Habitable).unwrap(), "\"habitable\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Blocker).unwrap(), "\"blocker\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Door).unwrap(), "\"door\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Trigger).unwrap(), "\"trigger\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Vehicle).unwrap(), "\"vehicle\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Spawner).unwrap(), "\"spawner\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Producer).unwrap(), "\"producer\"");
        assert_eq!(serde_json::to_string(&ObjectPrimitive::Plant).unwrap(), "\"plant\"");
    }

    #[test]
    fn object_walkability_defaults_match_design() {
        // Walkable: decoration, pickup, container, habitable, trigger, vehicle, producer
        assert!(ObjectPrimitive::Decoration.primitive_default_walkable());
        assert!(ObjectPrimitive::Pickup.primitive_default_walkable());
        assert!(ObjectPrimitive::Container.primitive_default_walkable());
        assert!(ObjectPrimitive::Habitable.primitive_default_walkable());
        assert!(ObjectPrimitive::Trigger.primitive_default_walkable());
        assert!(ObjectPrimitive::Vehicle.primitive_default_walkable());
        assert!(ObjectPrimitive::Producer.primitive_default_walkable());
        // Non-walkable: blocker, door (default closed), spawner, plant
        assert!(!ObjectPrimitive::Blocker.primitive_default_walkable());
        assert!(!ObjectPrimitive::Door.primitive_default_walkable());
        assert!(!ObjectPrimitive::Spawner.primitive_default_walkable());
        assert!(!ObjectPrimitive::Plant.primitive_default_walkable());
    }

    #[test]
    fn persistent_state_flag_matches_design() {
        // Stateful: container (loot), door (open/closed), vehicle (state),
        // spawner (cooldown), producer (resource buffer), plant (growth-stage)
        assert!(ObjectPrimitive::Container.has_persistent_state());
        assert!(ObjectPrimitive::Door.has_persistent_state());
        assert!(ObjectPrimitive::Vehicle.has_persistent_state());
        assert!(ObjectPrimitive::Spawner.has_persistent_state());
        assert!(ObjectPrimitive::Producer.has_persistent_state());
        assert!(ObjectPrimitive::Plant.has_persistent_state());
        // Stateless: decoration, pickup (one-shot, removed on consume),
        // habitable (state lives in child scene), blocker, trigger
        assert!(!ObjectPrimitive::Decoration.has_persistent_state());
        assert!(!ObjectPrimitive::Pickup.has_persistent_state());
        assert!(!ObjectPrimitive::Habitable.has_persistent_state());
        assert!(!ObjectPrimitive::Blocker.has_persistent_state());
        assert!(!ObjectPrimitive::Trigger.has_persistent_state());
    }
}
