package turn

import (
	"context"
	"sync"
	"time"
)

// TurnContextVersion is the wire-format version. V1 = stable.
const TurnContextVersion = 1

// TurnContext is the cross-service envelope carried with every request that
// participates in a turn. Versioned so we can add fields without breaking V1
// consumers (services pin to envelope_version >= 1).
type TurnContext struct {
	// EnvelopeVersion = 1 in V1.
	EnvelopeVersion int `json:"envelope_version"`

	// TurnID — UUID generated by the gateway at turn start. Same id flows
	// through every downstream call.
	TurnID string `json:"turn_id"`

	// SessionID — game session this turn belongs to.
	SessionID string `json:"session_id"`

	// RealityID — home reality.
	RealityID string `json:"reality_id"`

	// ActorID — user id (or service id for system-initiated turns).
	ActorID string `json:"actor_id"`

	// StartedAt — wall clock at turn admission.
	StartedAt time.Time `json:"started_at"`

	// State — current turn state. Mutated via Advance(), guarded by an
	// internal mutex so the same TurnContext can be passed across goroutines
	// without races. NOT Send-safe to mutate across await boundaries (Rust
	// mirror enforces this at compile time — Go relies on the mutex).
	state TurnState
	mu    sync.RWMutex
}

// NewTurnContext constructs a fresh TurnContext in StatePending.
func NewTurnContext(turnID, sessionID, realityID, actorID string, startedAt time.Time) *TurnContext {
	return &TurnContext{
		EnvelopeVersion: TurnContextVersion,
		TurnID:          turnID,
		SessionID:       sessionID,
		RealityID:       realityID,
		ActorID:         actorID,
		StartedAt:       startedAt,
		state:           StatePending,
	}
}

// State returns the current turn state (snapshot).
func (c *TurnContext) State() TurnState {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.state
}

// Advance transitions the turn to the next state. Returns ErrInvalidTransition
// on an illegal transition. Concurrent callers serialize on the internal mutex.
func (c *TurnContext) Advance(to TurnState) error {
	c.mu.Lock()
	defer c.mu.Unlock()
	if err := AssertTransition(c.state, to); err != nil {
		return err
	}
	c.state = to
	return nil
}

// SetForceState sets the state without checking the transition graph. ONLY
// for replay / recovery code that loads a checkpoint. Production hot-path
// MUST use Advance.
func (c *TurnContext) SetForceState(s TurnState) error {
	if !s.IsValid() {
		return ErrInvalidTransition
	}
	c.mu.Lock()
	c.state = s
	c.mu.Unlock()
	return nil
}

// ── Context wiring ──────────────────────────────────────────────────────────

type turnCtxKey struct{}

// WithTurnContext attaches a TurnContext to a request context.
func WithTurnContext(parent context.Context, tc *TurnContext) context.Context {
	return context.WithValue(parent, turnCtxKey{}, tc)
}

// FromContext extracts the TurnContext (nil if absent).
func FromContext(ctx context.Context) *TurnContext {
	v := ctx.Value(turnCtxKey{})
	if v == nil {
		return nil
	}
	tc, _ := v.(*TurnContext)
	return tc
}
