//! TMP_005 §6 — the V1+30d engine biome library + §2.3 default selection rules.
//!
//! A faithful-but-compact realization of the §6 table: every land terrain gets
//! a `Mountain` / `Tree` / `Rock` / `Plant` / `Lake` / `Crater` biome; `Water`
//! gets `Mountain` / `Rock` / `Plant` / `Lake` — its `Tree` and `Crater` reach
//! a `Water` zone via the §9 Q3 fallback. Each `BiomeSet` ships 4 rectangular
//! all-blocking templates sized per §2.1. The library is generated by a
//! deterministic loop — same call ⇒ equal `Vec`.

use std::collections::BTreeSet;

use crate::types::biome::{
    BiomeId, BiomeLevel, BiomeObjectType, BiomePriority, BiomeSelectionRule, BiomeSet,
};
use crate::types::object_template::{FootprintCell, TilemapObjectTemplate};
use crate::types::tile::TerrainKind;

/// The 7 land terrains (every surface `TerrainKind` except `Water`, plus the
/// V3 `Subterranean` and the RoadPlacer-only `Road` are excluded).
const LAND_TERRAINS: [TerrainKind; 7] = [
    TerrainKind::Grass,
    TerrainKind::Forest,
    TerrainKind::Mountain,
    TerrainKind::Sand,
    TerrainKind::Snow,
    TerrainKind::Swamp,
    TerrainKind::Rough,
];

/// A rectangular all-blocking `w × h` object template.
fn rect(name: String, w: i32, h: i32) -> TilemapObjectTemplate {
    let cells = (0..h)
        .flat_map(|dy| (0..w).map(move |dx| FootprintCell { dx, dy, blocking: true }))
        .collect();
    TilemapObjectTemplate { name, cells }
}

/// The 4 footprint `(w, h)` sizes for a biome object type — sized per TMP_005
/// §2.1 (Mountain 4-9 tiles, Tree 2-6, Lake 4-9, Rock 1-3, Plant 1-2, …).
fn template_sizes(object_type: BiomeObjectType) -> [(i32, i32); 4] {
    match object_type {
        BiomeObjectType::Mountain => [(2, 2), (2, 3), (3, 2), (3, 3)],
        BiomeObjectType::Lake => [(2, 2), (3, 2), (2, 3), (3, 3)],
        BiomeObjectType::Crater => [(2, 2), (2, 3), (3, 2), (3, 3)],
        BiomeObjectType::Tree => [(1, 2), (2, 2), (1, 3), (2, 3)],
        BiomeObjectType::Structure => [(1, 1), (1, 2), (2, 1), (2, 2)],
        BiomeObjectType::Rock => [(1, 1), (1, 2), (2, 1), (1, 3)],
        BiomeObjectType::Plant | BiomeObjectType::Animal => [(1, 1), (1, 1), (1, 2), (2, 1)],
        BiomeObjectType::Other => [(1, 1), (1, 1), (1, 1), (1, 1)],
    }
}

/// Stable lowercase tag for a biome object type — used in biome / template ids.
fn object_tag(object_type: BiomeObjectType) -> &'static str {
    match object_type {
        BiomeObjectType::Mountain => "mountain",
        BiomeObjectType::Tree => "tree",
        BiomeObjectType::Lake => "lake",
        BiomeObjectType::Crater => "crater",
        BiomeObjectType::Rock => "rock",
        BiomeObjectType::Plant => "plant",
        BiomeObjectType::Structure => "structure",
        BiomeObjectType::Animal => "animal",
        BiomeObjectType::Other => "other",
    }
}

/// Build one `BiomeSet` for a `(terrain, object_type)` cell — 4 templates sized
/// per §2.1, biome id `"{terrain}_{object}"`.
fn make_biome(terrain: TerrainKind, object_type: BiomeObjectType) -> BiomeSet {
    let tag = object_tag(object_type);
    let templates = template_sizes(object_type)
        .into_iter()
        .enumerate()
        .map(|(i, (w, h))| rect(format!("{}_{tag}_{}", terrain.tag(), i + 1), w, h))
        .collect();
    BiomeSet {
        biome_id: BiomeId(format!("{}_{tag}", terrain.tag())),
        terrain_types: BTreeSet::from([terrain]),
        level: BiomeLevel::Surface,
        factions: BTreeSet::new(),
        alignments: BTreeSet::new(),
        object_type,
        templates,
    }
}

/// TMP_005 §6 — the V1+30d engine biome library.
///
/// Land terrains get `Mountain` / `Tree` / `Rock` / `Plant` / `Lake` / `Crater`
/// biomes; `Water` gets those minus `Tree` and `Crater` (both reach a `Water`
/// zone via the §9 Q3 fallback). `Crater` IS stocked — though a less-common
/// feature — because the §2.3 `Lake xor Crater` pair needs it: with `Crater`
/// absent, a "Crater" two-coin outcome yields nothing AND suppresses `Lake`,
/// collapsing D3's ≈50 % water-feature slot to ≈25 %. `Structure` / `Animal` /
/// `Other` stay unstocked V1+30d — their §2.3 rules are plain `count_min: 0`
/// with no xor coupling, so an unstocked type simply yields none. Deterministic.
pub fn engine_biome_library() -> Vec<BiomeSet> {
    let mut library = Vec::new();
    for &terrain in &LAND_TERRAINS {
        for object_type in [
            BiomeObjectType::Mountain,
            BiomeObjectType::Tree,
            BiomeObjectType::Rock,
            BiomeObjectType::Plant,
            BiomeObjectType::Lake,
            BiomeObjectType::Crater,
        ] {
            library.push(make_biome(terrain, object_type));
        }
    }
    // Water — no `Tree`, no `Crater` (TMP_005 §6 Water row; both reach a Water
    // zone via the §9 Q3 fallback).
    for object_type in [
        BiomeObjectType::Mountain,
        BiomeObjectType::Rock,
        BiomeObjectType::Plant,
        BiomeObjectType::Lake,
    ] {
        library.push(make_biome(TerrainKind::Water, object_type));
    }
    library
}

/// TMP_005 §2.3 — the engine-default biome-selection rules (used when a zone's
/// `BiomeSelectionRules.use_engine_default` is true or it declares none).
pub fn engine_default_biome_selection_rules() -> Vec<BiomeSelectionRule> {
    use BiomeObjectType::*;
    use BiomePriority::*;
    let rule = |object_type, count_min, count_max, xor_with, priority| BiomeSelectionRule {
        object_type,
        count_min,
        count_max,
        xor_with,
        priority,
    };
    vec![
        // Large frame objects, picked first.
        rule(Mountain, 1, 1, None, First),
        rule(Tree, 1, 2, None, First),
        rule(Lake, 0, 1, Some(Crater), First),
        rule(Crater, 0, 1, Some(Lake), First),
        // Small filler.
        rule(Plant, 1, 2, None, Normal),
        rule(Rock, 1, 2, None, Normal),
        // Optional ambient.
        rule(Structure, 0, 1, None, Normal),
        rule(Animal, 0, 1, None, Normal),
        // Rare last-pick.
        rule(Other, 0, 1, None, Last),
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn library_covers_every_land_terrain_with_the_required_object_types() {
        // AC-1 — every land terrain has ≥1 Mountain / Tree / Rock / Plant /
        // Crater biome. Crater is required (not optional filler): the §2.3
        // `Lake xor Crater` pair needs a real Crater biome — an unstocked
        // Crater collapses D3's ≈50 % water-feature slot to ≈25 %.
        let library = engine_biome_library();
        for &terrain in &LAND_TERRAINS {
            for required in [
                BiomeObjectType::Mountain,
                BiomeObjectType::Tree,
                BiomeObjectType::Rock,
                BiomeObjectType::Plant,
                BiomeObjectType::Crater,
            ] {
                assert!(
                    library
                        .iter()
                        .any(|b| b.terrain_types.contains(&terrain) && b.object_type == required),
                    "{terrain:?} has no {required:?} biome",
                );
            }
        }
    }

    #[test]
    fn water_has_mountain_rock_plant_but_no_tree_or_crater() {
        // AC-1 — TMP_005 §6's Water row: no Tree, and no Crater (a land
        // feature). A Water zone's Tree and Crater both reach it via the §9 Q3
        // fallback.
        let library = engine_biome_library();
        let water: Vec<_> = library
            .iter()
            .filter(|b| b.terrain_types.contains(&TerrainKind::Water))
            .collect();
        for required in [BiomeObjectType::Mountain, BiomeObjectType::Rock, BiomeObjectType::Plant] {
            assert!(water.iter().any(|b| b.object_type == required), "Water lacks {required:?}");
        }
        for absent in [BiomeObjectType::Tree, BiomeObjectType::Crater] {
            assert!(
                !water.iter().any(|b| b.object_type == absent),
                "Water must have no {absent:?} biome (§6)",
            );
        }
    }

    #[test]
    fn every_biome_set_has_4_to_10_templates() {
        // AC-1 — TMP_005 §2.1 pins 4-10 templates per set.
        for biome in engine_biome_library() {
            let n = biome.templates.len();
            assert!((4..=10).contains(&n), "{:?} has {n} templates", biome.biome_id);
            assert!(!biome.terrain_types.is_empty());
            assert!(matches!(biome.level, BiomeLevel::Surface | BiomeLevel::Both));
            // every template has a non-empty footprint
            assert!(biome.templates.iter().all(|t| !t.cells.is_empty()));
        }
    }

    #[test]
    fn library_is_deterministic() {
        // AC-1 — same call ⇒ equal Vec.
        assert_eq!(engine_biome_library(), engine_biome_library());
    }

    #[test]
    fn default_rules_match_tmp005_section_2_3() {
        // AC-2 — the 9 §2.3 rules with the documented counts / priorities / xor.
        let rules = engine_default_biome_selection_rules();
        assert_eq!(rules.len(), 9);
        let find = |t| rules.iter().find(|r| r.object_type == t).unwrap();
        let mountain = find(BiomeObjectType::Mountain);
        assert_eq!((mountain.count_min, mountain.count_max), (1, 1));
        assert_eq!(mountain.priority, BiomePriority::First);
        let tree = find(BiomeObjectType::Tree);
        assert_eq!((tree.count_min, tree.count_max), (1, 2));
        let lake = find(BiomeObjectType::Lake);
        assert_eq!(lake.xor_with, Some(BiomeObjectType::Crater));
        assert_eq!((lake.count_min, lake.count_max), (0, 1));
        let crater = find(BiomeObjectType::Crater);
        assert_eq!(crater.xor_with, Some(BiomeObjectType::Lake));
        let other = find(BiomeObjectType::Other);
        assert_eq!(other.priority, BiomePriority::Last);
    }
}
