"""Generate a 256×128 hand-coded Earth biome reference image.

The image is the ground truth for `scripts/climate_eval.py` — its purpose is
to derive per-lat-band biome distribution + continentality patterns that the
procedural worldgen is scored against. It does NOT need to be a photorealistic
Earth map (our worlds have random continents); it needs to have the
**statistical structure** of Earth's biomes:
  - Lat banding (tropics / subtropics / mid-lat / boreal / polar)
  - Continental interiors drier than coasts (HotDesert at 25°N + interior)
  - Glacial caps at poles
  - Snow caps on mountain belts (placeholder via tall altitude bands)

Source references for biome placement:
  - Olson, D. M. et al. (2001). "Terrestrial Ecoregions of the World."
    BioScience 51 (11): 933-938.
  - Beck, H. E. et al. (2018). "Present and future Köppen-Geiger climate
    classification maps at 1-km resolution." Scientific Data 5: 180214.
  - Whittaker, R. H. (1975). "Communities and Ecosystems."

The image is regenerated by running this script; output is committed to
`eval/earth_reference.png`. Re-run only if Earth-target tuning changes.
"""

from PIL import Image
from pathlib import Path

# Same palette as `flat_climate::Biome::color()` — direct visual compare.
BIOMES = {
    "Ice":                [232, 238, 242],
    "Tundra":             [184, 183, 174],
    "BorealForest":       [74, 107, 71],
    "TemperateForest":    [79, 139, 65],
    "TemperateGrassland": [184, 180, 90],
    "HotDesert":          [216, 144, 96],   # B5 v2.1a W7 reddish
    "Savanna":            [201, 192, 74],
    "TropicalRainforest": [15, 77, 26],
}
OCEAN = [12, 16, 28]   # match flatworld VOID_COLOR

W, H = 256, 128


def lat_for(y: int) -> float:
    """Return latitude (°N+, °S-) for image row y. y=0 is 90°N, y=H is 90°S."""
    return 90.0 - (y / H) * 180.0


def biome_at(x: int, y: int) -> str | None:
    """Pick the biome (or None for ocean) at image pixel (x, y).

    The world has 3 simplified continents (Americas+Pacific bias / Eurasia-
    Africa / Australia) so coast vs interior contrasts are exhibited, plus
    Antarctica at the bottom. Each continent's biome distribution follows
    Earth's real lat-band placements + a continentality gradient inward.
    """
    lat = lat_for(y)
    abs_lat = abs(lat)

    # ---- Antarctica (south of -65°) ----
    if lat < -65:
        return "Ice"

    # ---- Continents — 3 strips by x ----
    # Americas (x 10-70), Eurasia-Africa (x 80-180), Australia (x 200-235)
    in_americas = 10 <= x <= 70
    in_eurasia = 80 <= x <= 180
    in_australia = 200 <= x <= 235 and lat < 0 and lat > -45

    if not (in_americas or in_eurasia or in_australia):
        return None  # ocean

    # Continent-relative coast distance (px from nearest land edge of THIS continent).
    if in_americas:
        edge_dist = min(x - 10, 70 - x)
        width = 60
    elif in_eurasia:
        edge_dist = min(x - 80, 180 - x)
        width = 100
    else:  # Australia
        edge_dist = min(x - 200, 235 - x)
        width = 35
    cont_frac = max(0.0, min(1.0, edge_dist / (width / 2.0)))
    is_interior = cont_frac > 0.55

    # ---- Lat banding (per Earth) ----
    # Greenland-style ice cap on far-northern Eurasia (Arctic Ocean fringe)
    if abs_lat > 75 and in_eurasia:
        return "Ice"
    # Tundra band — polar fringe
    if abs_lat > 65:
        return "Tundra"
    # Boreal forest band — sub-arctic (50-65°)
    if 50 <= abs_lat <= 65:
        # Most northern continent area; some Tundra near coast on Eurasia
        if in_eurasia and abs_lat > 60 and not is_interior:
            return "Tundra"
        return "BorealForest"
    # Mid-lat (30-50°) — TemperateForest at coast, TempGrassland interior,
    # HotDesert in continental rain shadows.
    if 30 <= abs_lat < 50:
        if is_interior:
            # Eurasia has Gobi / Central Asian deserts at this lat
            if in_eurasia and abs_lat < 45:
                return "HotDesert"
            return "TemperateGrassland"
        return "TemperateForest"
    # Subtropics (20-30°) — HotDesert belt (Sahara, Arabian, Mexican)
    if 20 <= abs_lat < 30:
        # Coastal Mediterranean = TempForest fringe, but for simplicity
        # treat all subtropical land as HotDesert/Savanna split by interior.
        if is_interior:
            return "HotDesert"
        return "Savanna"
    # Tropical (10-20°) — Savanna belt
    if 10 <= abs_lat < 20:
        if in_americas and lat < 0:  # Amazon basin
            return "TropicalRainforest"
        return "Savanna"
    # Equatorial (<10°) — TropicalRainforest dominant
    if abs_lat < 10:
        # Africa Sahel transition (north equator part of Eurasia-Africa)
        if in_eurasia and lat > 5:
            return "Savanna"
        return "TropicalRainforest"

    return "TemperateGrassland"  # fallback shouldn't fire


def main():
    img = Image.new("RGB", (W, H), tuple(OCEAN))
    pixels = img.load()
    for y in range(H):
        for x in range(W):
            b = biome_at(x, y)
            if b is None:
                pixels[x, y] = tuple(OCEAN)
            else:
                pixels[x, y] = tuple(BIOMES[b])

    out = Path(__file__).resolve().parent.parent / "eval" / "earth_reference.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    img.save(out)
    print(f"wrote {out} — {W}×{H}, biomes hand-coded per Olson 2001 + Beck 2018")


if __name__ == "__main__":
    main()
