#!/usr/bin/env python3
"""i18n-completeness-gate.py — ENFORCE ML-7 (docs/standards/multilingual.md).

The rule: `en` is the ONLY hand-authored locale; every other uiLocale is GENERATED by
`scripts/i18n_translate.py` (gap-fill, reasoning-off, verify+self-heal, no silent blanks). The
failure this catches: someone adds/edits a key in `en/<ns>.json` and commits WITHOUT running the
tool, so the other locales silently miss it (or a one-off hand-written translator drifts). The ONLY
way to stay green is to run the tool — never reinvent it, never hand-edit a non-`en` locale.

Checks, for each namespace touched:
  • every `en/<ns>.json` STRING key exists + is non-empty in every uiLocale, AND
  • no uiLocale ships a non-empty `<lang>/_FAILED.json`.

`--staged` (pre-commit): only gate namespaces whose `en/<ns>.json` (or a locale file / _FAILED) is
staged — so a commit that adds en copy without regenerating locales fails AT the point of violation,
while pre-existing gaps in untouched namespaces don't block an unrelated commit. No args = full repo
scan (CI). Cross-platform, stdlib-only (mirrors ai-provider-gate.py / language-bias-gate.py)."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# EVERY locale tree in the repo, not just the novel app's.
#
# This was a single hardcoded path (`frontend/src/i18n/locales`) until a SECOND
# tree appeared for the game client (`packages/i18n/locales`, 2026-07-30). The
# staged-path filter below matched on the substring "/i18n/locales/", which is
# present in BOTH — so staging a game locale made the gate check the *novel*
# app's tree and report OK, a green that proved nothing about the file actually
# being committed. A game-only namespace (no counterpart under frontend/) passed
# silently even with zero translations, because it matched no `en` namespace in
# the only tree the gate could see.
#
# Roots are (relative-path-prefix, absolute-dir). The prefix scopes the staged
# filter so the trees can never validate each other again.
LOCALE_ROOTS = [
    ("frontend/src/i18n/locales/", REPO / "frontend" / "src" / "i18n" / "locales"),
    ("packages/i18n/locales/", REPO / "packages" / "i18n" / "locales"),
]
SRC = "en"


def flatten(obj, prefix: str = "") -> dict:
    out: dict = {}
    if isinstance(obj, dict):
        for k, v in obj.items():
            out.update(flatten(v, f"{prefix}.{k}" if prefix else k))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            out.update(flatten(v, f"{prefix}[{i}]"))
    else:
        out[prefix] = obj
    return out


def _load(path: Path) -> dict:
    return flatten(json.loads(path.read_text(encoding="utf-8")))


def staged_files() -> set[str]:
    try:
        out = subprocess.run(["git", "diff", "--cached", "--name-only"],
                             cwd=REPO, capture_output=True, text=True, check=True).stdout
    except Exception:
        return set()
    return {ln.strip().replace("\\", "/") for ln in out.splitlines() if ln.strip()}


def check_root(prefix: str, LOCALES: Path, staged_mode: bool, sf: set) -> tuple[list, int, int]:
    """Check one locale tree. Returns (problems, n_locales, n_namespaces_checked)."""
    en_dir = LOCALES / SRC
    if not en_dir.is_dir():
        return ([], 0, 0)
    all_ns = sorted(f.name for f in en_dir.glob("*.json"))
    locales = sorted(d.name for d in LOCALES.iterdir()
                     if d.is_dir() and d.name != SRC and not d.name.startswith("_"))

    # In --staged mode, only gate namespaces whose en (or any locale copy / _FAILED) is staged.
    # The filter is anchored to THIS root's prefix so a sibling tree's staged file
    # can never select namespaces here.
    ns_to_check = all_ns
    if staged_mode:
        touched = {p.rsplit("/", 1)[-1] for p in sf
                   if p.startswith(prefix) and p.endswith(".json") and not p.endswith("_FAILED.json")}
        failed_touched = any(p.startswith(prefix) and p.endswith("_FAILED.json") for p in sf)
        # A staged namespace with NO `en` counterpart is itself a violation: en is
        # the authored source, so a translation with no source cannot be correct.
        orphans = sorted(touched - set(all_ns))
        ns_to_check = [ns for ns in all_ns if ns in touched]
        if not ns_to_check and not failed_touched and not orphans:
            return ([], len(locales), 0)
        if orphans:
            return ([f"{prefix}{o} — staged with no `en/{o}` source (ML-7: en is authored first)"
                     for o in orphans], len(locales), len(ns_to_check))

    problems: list[str] = []
    for loc in locales:
        fp = LOCALES / loc / "_FAILED.json"
        if fp.exists():
            try:
                fj = json.loads(fp.read_text(encoding="utf-8"))
                n = sum(len(v) for v in fj.values()) if isinstance(fj, dict) else 0
                if n:
                    problems.append(f"{loc}/_FAILED.json — {n} unresolved keys (re-run the tool)")
            except Exception:
                pass
        for ns in ns_to_check:
            en_keys = {k for k, v in _load(en_dir / ns).items() if isinstance(v, str)}
            lp = LOCALES / loc / ns
            if not lp.exists():
                problems.append(f"{loc}/{ns} — MISSING ({len(en_keys)} en keys)")
                continue
            lf = _load(lp)
            missing = [k for k in en_keys if not (isinstance(lf.get(k), str) and lf[k])]
            if missing:
                problems.append(f"{loc}/{ns} — {len(missing)} missing/empty (e.g. {sorted(missing)[:3]})")

    return ([f"{prefix}{p}" for p in problems], len(locales), len(ns_to_check))


def main() -> int:
    staged_mode = "--staged" in sys.argv
    sf = staged_files() if staged_mode else set()

    problems: list[str] = []
    n_loc = n_ns = 0
    for prefix, root in LOCALE_ROOTS:
        probs, nl, nn = check_root(prefix, root, staged_mode, sf)
        problems += probs
        n_loc += nl
        n_ns += nn

    if problems:
        scope = "staged" if staged_mode else "full-repo"
        print(f"i18n-completeness-gate ({scope}): FAIL — ML-7 violated. "
              f"Run: python scripts/i18n_translate.py")
        for p in problems[:60]:
            print(f"  ✗ {p}")
        if len(problems) > 60:
            print(f"  … +{len(problems) - 60} more")
        return 1

    print(f"i18n-completeness-gate: OK — {len(LOCALE_ROOTS)} tree(s), "
          f"{n_loc} locale-dir(s) x {n_ns} namespace(s) at full `en` parity")
    return 0


if __name__ == "__main__":
    sys.exit(main())
