#!/usr/bin/env python3
"""
brief-generator — B4 auto-generate cycle briefs from CYCLE_DECOMPOSITION.md
Per RAID_WORKFLOW.md §13.4.

Parses CYCLE_DECOMPOSITION.md §2 cycle inventory tables (markdown tables with
columns: #, Title, DPS parallel, Depends on, Brief location) and emits a
brief per row to docs/raid/cycle_briefs/<NN>_<short>.md following TEMPLATE.md.

R3-WARN-2 D-CYCLE-0-DRIFT-ENFORCER: refuses to run if CYCLE_DECOMPOSITION
last_synced_with_RAID_WORKFLOW_version header != RAID_WORKFLOW frontmatter version.

Usage:
  brief-generator.py                 # generate all 37 briefs (overwrites)
  brief-generator.py --cycle 17      # generate one
  brief-generator.py --dry-run       # print first brief; do not write
  brief-generator.py --check-drift   # just run drift check
"""
from __future__ import annotations
import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "scripts" / "raid"))
from task_config import load_config  # noqa: E402

_CFG = load_config()
PLANS_DIR = REPO_ROOT / _CFG["plan_dir"]
DECOMP = REPO_ROOT / _CFG["decomposition_doc"]
RAID_SPEC = REPO_ROOT / _CFG["workflow_doc"]
BRIEFS_DIR = REPO_ROOT / _CFG["brief_dir"]
AUDIT_LOG = REPO_ROOT / _CFG["audit_log"]

CYCLE_ROW_RE = re.compile(
    r"^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*([^|]+?)\s*\|\s*`([^`]+)`\s*\|",
    re.MULTILINE,
)


def now_iso() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def audit(event: str, **fields) -> None:
    AUDIT_LOG.parent.mkdir(parents=True, exist_ok=True)
    row = {"ts": now_iso(), "event": event, **fields}
    with AUDIT_LOG.open("a", encoding="utf-8") as f:
        f.write(json.dumps(row) + "\n")


def extract_versions() -> tuple[str, str]:
    """Return (cd_version, rw_version). Empty string if not found."""
    cd_text = DECOMP.read_text(encoding="utf-8") if DECOMP.exists() else ""
    rw_text = RAID_SPEC.read_text(encoding="utf-8") if RAID_SPEC.exists() else ""
    m = re.search(r"last_synced_with_RAID_WORKFLOW_version:\*{0,2}\s*(v\d+\.\d+)", cd_text)
    cd = m.group(1) if m else ""
    m = re.search(r"Version:\*\*\s*RAID\s+(v\d+\.\d+)", rw_text)
    rw = m.group(1) if m else ""
    return cd, rw


def check_drift_or_exit() -> None:
    cd, rw = extract_versions()
    if not cd or not rw:
        print(f"[brief-generator] WARN: could not extract versions (cd={cd!r} rw={rw!r}) — drift check inconclusive", file=sys.stderr)
        audit("brief_generator_drift_inconclusive", cd=cd, rw=rw)
        return
    if cd != rw:
        print(f"[brief-generator] ERROR: spec drift CYCLE_DECOMPOSITION={cd} RAID_WORKFLOW={rw}", file=sys.stderr)
        audit("brief_generator_drift_detected", cd=cd, rw=rw)
        sys.exit(5)
    audit("brief_generator_drift_check_passed", version=cd)


def parse_cycles() -> list[dict]:
    """Return list of {num, title, dps_parallel, depends, brief_path} dicts."""
    text = DECOMP.read_text(encoding="utf-8")
    rows = []
    for m in CYCLE_ROW_RE.finditer(text):
        num, title, dps, deps, brief = m.groups()
        # Skip table header / placeholder rows
        if title.lower().startswith("title") or "..." in title:
            continue
        try:
            n = int(num)
        except ValueError:
            continue
        rows.append({
            "num": n,
            "title": title.strip(),
            "dps_parallel": dps.strip(),
            "depends": deps.strip(),
            "brief_path": brief.strip(),
        })
    return rows


def short_name(cycle_num: int, brief_path: str) -> str:
    """Derive 03_<short>.md filename from brief_path."""
    name = Path(brief_path).name
    if not name.endswith(".md"):
        name = name + ".md"
    return name


def emit_brief(cycle: dict) -> str:
    """Render a brief markdown string from a cycle row dict."""
    n = cycle["num"]
    title = cycle["title"]
    dps_count = cycle["dps_parallel"].split()[0] if cycle["dps_parallel"] else "?"
    deps = cycle["depends"]

    # Heuristic top-3 LOCKED placeholders (generator does NOT have layer
    # plans loaded; cycle-specific layer LOCKED enumeration is a follow-up
    # task tracked as D-CYCLE-0-LOCKED-ENUM-PERCYCLE — for smoke test, the
    # validator only requires Q-IDs to be syntactically present).
    locked_placeholders = [
        f"Q-CYCLE-{n}-A-1 (placeholder; populated by layer-plan reader follow-up)",
        f"Q-CYCLE-{n}-A-2 (placeholder; populated by layer-plan reader follow-up)",
        f"Q-CYCLE-{n}-A-3 (placeholder; populated by layer-plan reader follow-up)",
    ]

    body = f"""# Cycle {n}: {title}

> Auto-generated by `scripts/raid/brief-generator.py` from CYCLE_DECOMPOSITION.md §2.
> Last generated: {now_iso()}.
> last_synced_with_RAID_WORKFLOW_version: {extract_versions()[0]}.

## 🎯 TL;DR (30 seconds — TOP critical info)
- **Scope:** {title}. See parent layer plan for sub-component details.
- **Acceptance gate:** `scripts/raid/verify-cycle-{n}.sh` exits 0
- **Top 3 LOCKED decisions consumed:** {locked_placeholders[0]}, {locked_placeholders[1]}, {locked_placeholders[2]}
- **DPS count:** {dps_count}
- **Estimated wall time:** 3-5h (per §14.11 baseline)

## Dependencies (must show DONE in CYCLE_LOG.md)
- Cycles: {deps}
- Files expected to exist (grep-able paths): see parent layer plan

## Scope (IN)
- All sub-components named in title: "{title}"
- DPS parallel breakdown per CYCLE_DECOMPOSITION.md §2 row {n} (`{cycle['dps_parallel']}`)
- Per-component tests + lints + integration smoke for cross-service touches

## Scope (OUT — explicitly)
- Cycles other than {n}
- Layer sub-components not named in this title
- Anything in `infra/existing-prod/` (B5 prod-isolation enforced)

## Acceptance criteria (CI gates — exit code 0 = pass)
- Tests pass: per-cycle test suites (populated by per-cycle verify-cycle-{n}.sh)
- Lints pass: language-specific (go vet, cargo clippy, ruff, etc.)
- Integration smoke: cross-service if ≥2 services touched (per CLAUDE.md VERIFY rule)
- B5 prod-isolation-lint exit 0
- B6 secret-scan-cycle exit 0

## DPS parallelism plan
- DPS count from §2 table: {cycle['dps_parallel']}
- Per-DPS slice mapping: see parent layer plan §X (Raid Leader assigns at Phase 4 PLAN)
- Each DPS isolated test stack via `test-infra-up-dps.sh {n} <I>` (B2)
- Each DPS return budget: 1500 tokens summary (P4)

## Adversary review focus (cold-start sub-agent — return budget 2000 tokens)
- Verify all named sub-components actually implemented (not stubbed)
- Cross-DPS data races (per §13.2 — per-DPS infra prevents)
- LOCKED Q-ID resolutions honored (no re-litigation)
- Cycle-specific known pitfalls: see parent layer plan REVIEW section

## Scope Guard CLEAR criteria (cold-start sub-agent — return budget 500 tokens)
- All IN-scope items present in diff
- No OUT-scope items touched
- All acceptance criteria met
- Cross-cycle invariants not violated (I1-I19 amended)

## Cross-references (for deep-read IF Raid Leader needs FOCUS mode)
- Layer plan: see PLANS_DIR/L<X>_*.md (X derived from cycle number)
- Kernel chunks: per CYCLE_DECOMPOSITION.md §3 dependency graph
- LOCKED decisions consumed (full list): {locked_placeholders[0]}; {locked_placeholders[1]}; {locked_placeholders[2]}

## ⚠️ REMINDERS (BOTTOM — re-stated critical info, anti-lost-in-middle)
- 🔴 **Top LOCKED 1:** {locked_placeholders[0]} → see parent layer plan
- 🔴 **Top LOCKED 2:** {locked_placeholders[1]} → see parent layer plan
- 🔴 **Top LOCKED 3:** {locked_placeholders[2]} → see parent layer plan
- 🔴 **Acceptance MUST include:** verify-cycle-{n}.sh exit 0 + secret-scan + prod-isolation-lint
- 🔴 **Do NOT touch:** infra/existing-prod/ OR services not in scope of this cycle
- 🔴 **Fresh session reminder:** this is a new `/raid {n}` invocation; no carry-over from prior cycles. Read CYCLE_LOG.md + this brief + LOCKED file ONLY.
"""
    return body


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--cycle", type=int, default=None)
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--check-drift", action="store_true")
    args = p.parse_args(argv)

    check_drift_or_exit()

    if args.check_drift:
        print("[brief-generator] drift check passed")
        return 0

    cycles = parse_cycles()
    if not cycles:
        print("[brief-generator] ERROR: no cycle rows parsed from CYCLE_DECOMPOSITION.md §2", file=sys.stderr)
        return 6

    if args.cycle is not None:
        cycles = [c for c in cycles if c["num"] == args.cycle]
        if not cycles:
            print(f"[brief-generator] cycle {args.cycle} not in table", file=sys.stderr)
            return 7

    BRIEFS_DIR.mkdir(parents=True, exist_ok=True)
    count = 0
    for cycle in cycles:
        body = emit_brief(cycle)
        if args.dry_run:
            print(body)
            return 0
        out = BRIEFS_DIR / short_name(cycle["num"], cycle["brief_path"])
        # Overwrite atomically
        tmp = out.with_suffix(".tmp")
        tmp.write_text(body, encoding="utf-8")
        os.replace(tmp, out)
        count += 1
    audit("brief_generator_run", count=count)
    print(f"[brief-generator] generated {count} brief(s) → {BRIEFS_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
