#!/usr/bin/env bash
# recover-from-crash — operator-only crash recovery toolkit
# Per RAID_WORKFLOW.md v1.4 §13.7 crash-recovery table + R3 D-CYCLE-0-PID-FILE-CONTRACT
#
# Sub-commands:
#   --inspect                  print lock + signal + pid state + last 10 audit rows
#   --reset-lock               force lock=UNLOCKED (requires no active /raid session)
#   --rewrite-signal <N>       regenerate signal file for cycle N from CYCLE_LOG state
#
# Refusal logic (R3-WARN-3):
#   Reads docs/raid/.raid-session.pid; if PID alive (kill -0 PID == 0),
#   refuses with error. If pid file exists but process dead, audit-log
#   event=stale_pid_cleaned and proceed.
set -euo pipefail
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
RAID_DIR="$REPO_ROOT/docs/raid"
LOCK_PATH="$RAID_DIR/.session-cycle-lock"
PID_PATH="$RAID_DIR/.raid-session.pid"
AUDIT_LOG="$REPO_ROOT/docs/audit/AUDIT_LOG.jsonl"
NOW="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

audit() {
  local event="$1"; local extra="${2:-}"
  mkdir -p "$(dirname "$AUDIT_LOG")"
  echo "{\"ts\":\"$NOW\",\"event\":\"$event\"${extra:+,$extra}}" >> "$AUDIT_LOG"
}

# Returns 0 if safe to proceed, 1 if active session blocks, 2 if pid stale (proceed but log)
check_pid() {
  if [ ! -f "$PID_PATH" ]; then
    return 0
  fi
  local pid
  pid="$(cat "$PID_PATH" 2>/dev/null | head -1 | tr -d '[:space:]')"
  if [ -z "$pid" ]; then
    rm -f "$PID_PATH"
    audit "stale_pid_cleaned" "\"reason\":\"empty_pid_file\""
    return 2
  fi
  if kill -0 "$pid" 2>/dev/null; then
    return 1
  fi
  rm -f "$PID_PATH"
  audit "stale_pid_cleaned" "\"reason\":\"process_dead\",\"pid\":$pid"
  return 2
}

read_lock() {
  if [ ! -f "$LOCK_PATH" ]; then echo "UNLOCKED"; return; fi
  grep -v '^[[:space:]]*#' "$LOCK_PATH" | grep -v '^[[:space:]]*$' | head -1 | tr -d '[:space:]' || echo "UNLOCKED"
}

write_lock() {
  local v="$1"
  printf '%s\n# Last updated: %s by recover-from-crash.sh\n' "$v" "$NOW" > "$LOCK_PATH.tmp"
  mv -f "$LOCK_PATH.tmp" "$LOCK_PATH"
}

cmd_inspect() {
  echo "=== RAID state inspection — $NOW ==="
  echo ""
  echo "Lock:        $(read_lock)"
  if [ -f "$PID_PATH" ]; then
    local pid; pid="$(cat "$PID_PATH" | head -1)"
    if kill -0 "$pid" 2>/dev/null; then
      echo "PID file:    $pid (ALIVE)"
    else
      echo "PID file:    $pid (DEAD — stale)"
    fi
  else
    echo "PID file:    (none)"
  fi
  echo ""
  echo "READY_FOR_CYCLE_* signals:"
  ls "$RAID_DIR"/READY_FOR_CYCLE_*.signal 2>/dev/null | sed 's/^/  /' || echo "  (none)"
  echo ""
  echo "Last 10 AUDIT_LOG rows:"
  if [ -f "$AUDIT_LOG" ]; then
    tail -10 "$AUDIT_LOG" | sed 's/^/  /'
  else
    echo "  (audit log absent)"
  fi
  audit "recover_inspect_run"
}

cmd_reset_lock() {
  check_pid; rc=$?
  if [ "$rc" = "1" ]; then
    local pid; pid="$(cat "$PID_PATH" | head -1)"
    echo "[recover] error: /raid session PID $pid active in another terminal — refusing --reset-lock" >&2
    audit "recover_refused" "\"reason\":\"active_session\",\"pid\":$pid"
    exit 1
  fi
  local before; before="$(read_lock)"
  write_lock "UNLOCKED"
  echo "[recover] lock reset: $before → UNLOCKED"
  audit "recover_reset_lock" "\"previous\":\"$before\""
}

cmd_rewrite_signal() {
  local target="${1:-}"
  if [ -z "$target" ]; then
    echo "usage: recover-from-crash.sh --rewrite-signal <cycle_number>" >&2
    exit 2
  fi
  check_pid; rc=$?
  if [ "$rc" = "1" ]; then
    local pid; pid="$(cat "$PID_PATH" | head -1)"
    echo "[recover] error: /raid session PID $pid active — refusing" >&2
    audit "recover_refused" "\"reason\":\"active_session\",\"pid\":$pid"
    exit 1
  fi
  local sig="$RAID_DIR/READY_FOR_CYCLE_${target}.signal"
  cat > "$sig" <<EOF
# Regenerated by recover-from-crash.sh --rewrite-signal $target at $NOW
schema_version: 1
next_cycle: $target
ready_at: $NOW
deps_satisfied: []
smoke_evidence_sha: REGENERATED
dispatcher_pid: -1
EOF
  echo "[recover] regenerated signal: $sig"
  audit "recover_rewrite_signal" "\"cycle\":$target"
}

# Main
case "${1:-}" in
  --inspect) cmd_inspect ;;
  --reset-lock) cmd_reset_lock ;;
  --rewrite-signal) shift; cmd_rewrite_signal "${1:-}" ;;
  *) echo "usage: recover-from-crash.sh {--inspect | --reset-lock | --rewrite-signal <N>}" >&2; exit 1 ;;
esac
