#!/usr/bin/env bash
# infra/prometheus/scrape-config-generator.sh — L7.H.3 (RAID cycle 33)
#
# Dynamic Prometheus scrape-target generator. Reads the L1.C provisioner
# registry (cycle 5) and emits one file_sd YAML per active reality.
#
# This script is invoked by:
#   1. cycle-5 provisioner's `register_prometheus_scrape` Effect
#      (the wiring deferred as D-PROVISIONER-PROM-SCRAPE-WIRING is the
#      bridge between provisioner Effect → this script execution).
#   2. SRE manually for full-resync after Prometheus restart.
#   3. cycle-33 verify (smoke generate against fixture provisioner state).
#
# Output directory: /etc/prometheus/targets/per-reality/<reality_id>.yaml
# (matches cycle-6 scrape-config.yaml file_sd_configs glob).
#
# Cycle-6 invariant: only `reality_id` and `shard_host` may carry per-reality
# dimensionality (cardinality control). This script enforces by emitting
# exactly those labels.

set -euo pipefail

TARGET_DIR="${LW_PROM_TARGET_DIR:-/etc/prometheus/targets/per-reality}"
REGISTRY_URL="${LW_PROVISIONER_REGISTRY_URL:-http://world-service.internal:8080/internal/realities}"
DRY_RUN="${LW_DRY_RUN:-0}"

usage() {
    echo "usage: scrape-config-generator.sh [--reality-id <id>] [--all]"
    echo "  --reality-id <id>    regenerate a single reality target file"
    echo "  --all                full resync (read registry, rewrite all files)"
    echo "  --validate <file>    validate a target file without writing"
    exit 2
}

mkdir -p "$TARGET_DIR"

emit_target_file() {
    local reality_id="$1"
    local shard_host="$2"
    local port="${3:-9187}"
    local out="${TARGET_DIR}/${reality_id}.yaml"
    cat > "$out" <<EOF
# Auto-generated by scrape-config-generator.sh — DO NOT EDIT.
# Reality: ${reality_id}
# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Cycle-6 cardinality invariant: only reality_id + shard_host labels here.
- targets:
    - ${shard_host}:${port}
  labels:
    reality_id: "${reality_id}"
    shard_host: "${shard_host}"
EOF
    echo "[scrape-config-generator] wrote $out"
}

validate_target_file() {
    local f="$1"
    if [ ! -f "$f" ]; then
        echo "[validate] $f not found" >&2
        return 1
    fi
    # Must contain reality_id label and shard_host label
    if ! grep -q 'reality_id:' "$f"; then
        echo "[validate] $f missing reality_id label" >&2
        return 1
    fi
    if ! grep -q 'shard_host:' "$f"; then
        echo "[validate] $f missing shard_host label" >&2
        return 1
    fi
    # Cardinality invariant — count labels; must be exactly 2.
    local label_count
    label_count=$(grep -c '^    [a-z_]*:' "$f" || true)
    if [ "$label_count" -ne 2 ]; then
        echo "[validate] $f has ${label_count} labels; cardinality invariant requires exactly 2" >&2
        return 1
    fi
    echo "[validate] $f OK"
    return 0
}

main() {
    case "${1:-}" in
        --reality-id)
            shift
            local reality_id="${1:-}"; shift || true
            local shard_host="${1:-shard-${reality_id}.internal}"
            if [ "$DRY_RUN" = "1" ]; then
                echo "[dry-run] would emit target file for reality_id=$reality_id shard_host=$shard_host"
            else
                emit_target_file "$reality_id" "$shard_host"
            fi
            ;;
        --all)
            echo "[scrape-config-generator] full resync from $REGISTRY_URL"
            # Foundation V1: registry call shape is JSON list of {reality_id, shard_host}.
            # Cycle 33 ships the bash skeleton; cycle 34 wires real provisioner.
            if command -v curl >/dev/null 2>&1; then
                if registry_json=$(curl -fsS "$REGISTRY_URL" 2>/dev/null); then
                    echo "$registry_json" | grep -oE '"reality_id":"[^"]+","shard_host":"[^"]+"' \
                        | while IFS= read -r line; do
                            local rid sh
                            rid=$(echo "$line" | sed -nE 's/.*"reality_id":"([^"]+)".*/\1/p')
                            sh=$(echo "$line"  | sed -nE 's/.*"shard_host":"([^"]+)".*/\1/p')
                            [ -n "$rid" ] && [ -n "$sh" ] && emit_target_file "$rid" "$sh"
                        done
                else
                    echo "[scrape-config-generator] registry unreachable — no-op (Prom file_sd glob preserves last-known)"
                fi
            else
                echo "[scrape-config-generator] curl absent — skipping" >&2
            fi
            ;;
        --validate)
            shift
            validate_target_file "${1:-}"
            ;;
        --smoke)
            # Cycle-33 verify smoke: emit a fixture file, validate, clean up.
            emit_target_file "smoke-test-reality" "shard-smoke.internal"
            validate_target_file "${TARGET_DIR}/smoke-test-reality.yaml"
            rm -f "${TARGET_DIR}/smoke-test-reality.yaml"
            ;;
        *)
            usage
            ;;
    esac
}

main "$@"
