package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/loreweave/foundation/contracts/events"
)

// EmitTypeScript writes TS interfaces to <outDir>/<event-kebab>.ts and an
// index.ts that re-exports all events.
//
// Scope per Q-L4-1: TS gets EVENT TYPES only (not full runtime types like
// Go/Rust/Python). The frontend uses these for WS envelope deserialization.
func EmitTypeScript(reg *events.Registry, outDir string) error {
	var allInterfaces []string
	for _, name := range reg.EventTypes() {
		e, _ := reg.LookupType(name)
		for _, v := range e.Versions {
			structName := structForVersion(e, v)
			fname := kebab(structName) + ".ts"
			content := renderTsInterface(e, v, structName)
			if err := os.WriteFile(filepath.Join(outDir, fname), []byte(content), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", fname, err)
			}
			allInterfaces = append(allInterfaces, fmt.Sprintf("export * from './%s';", kebab(structName)))
		}
	}
	// index.ts
	var ib strings.Builder
	ib.WriteString("// Code generated by eventgen v" + version + ". DO NOT EDIT.\n")
	ib.WriteString("// Re-generate: make eventgen\n\n")
	for _, line := range allInterfaces {
		ib.WriteString(line + "\n")
	}
	return os.WriteFile(filepath.Join(outDir, "index.ts"), []byte(ib.String()), 0o644)
}

func renderTsInterface(e *events.RegistryEntry, v uint32, structName string) string {
	var b strings.Builder
	b.WriteString("// Code generated by eventgen v" + version + ". DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Event: %s v%d\n", e.Name, v))
	b.WriteString(fmt.Sprintf("// %s\n\n", e.Description))
	b.WriteString(fmt.Sprintf("export interface %s {\n", structName))
	for _, f := range fieldsForEvent(e.Name, v) {
		b.WriteString(fmt.Sprintf("  %s: %s;\n", f.Name, f.TsType))
	}
	b.WriteString("}\n")
	return b.String()
}

// kebab converts CamelCase → kebab-case.
func kebab(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('-')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
