package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/loreweave/foundation/contracts/events"
)

// EmitRust writes Rust struct definitions to <outDir>/<event_snake>.rs and
// a `mod.rs` that re-exports them.
//
// Generated Rust shape (mirrors the Go struct minus binding annotations):
//
//	// Code generated by eventgen vX. DO NOT EDIT.
//	use serde::{Deserialize, Serialize};
//	use uuid::Uuid;
//
//	#[derive(Debug, Clone, Serialize, Deserialize)]
//	pub struct NpcSaidV2 {
//	    pub npc_id: Uuid,
//	    pub text: String,
//	    pub scene_id: Uuid,
//	    pub said_at: chrono::DateTime<chrono::Utc>,
//	    pub tone: String,
//	}
//
// Fields are inferred from the Go struct via stage-2 codegen in a later cycle.
// Cycle 8 V1 emits SKELETONS — pub struct + `pub field: <T>` — based on a
// hand-maintained per-event field map (see `rustFields`).
//
// FUTURE (cycle 12+ Track 4 ports): parse the Go AST and infer fields
// automatically. Tracked as D-EVENTGEN-RUST-AUTO-INFER.
func EmitRust(reg *events.Registry, outDir string) error {
	var modImports []string
	for _, name := range reg.EventTypes() {
		e, _ := reg.LookupType(name)
		for _, v := range e.Versions {
			structName := structForVersion(e, v)
			file := snake(structName) + ".rs"
			content := renderRustStruct(e, v, structName)
			if err := os.WriteFile(filepath.Join(outDir, file), []byte(content), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", file, err)
			}
			modImports = append(modImports, snake(structName))
		}
	}
	// mod.rs
	var mb strings.Builder
	mb.WriteString("// Code generated by eventgen v" + version + ". DO NOT EDIT.\n")
	mb.WriteString("// Re-generate: make eventgen\n\n")
	for _, m := range modImports {
		mb.WriteString(fmt.Sprintf("pub mod %s;\n", m))
	}
	mb.WriteString("\n")
	for _, m := range modImports {
		// pub use noisy::*; — but we'd need the struct name; do explicit re-exports.
		mb.WriteString(fmt.Sprintf("pub use %s::*;\n", m))
	}
	return os.WriteFile(filepath.Join(outDir, "mod.rs"), []byte(mb.String()), 0o644)
}

func renderRustStruct(e *events.RegistryEntry, v uint32, structName string) string {
	var b strings.Builder
	b.WriteString("// Code generated by eventgen v" + version + ". DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("// Event: %s v%d\n", e.Name, v))
	b.WriteString(fmt.Sprintf("// %s\n\n", e.Description))
	b.WriteString("use serde::{Deserialize, Serialize};\n")
	b.WriteString("use uuid::Uuid;\n\n")
	b.WriteString("#[derive(Debug, Clone, Serialize, Deserialize)]\n")
	b.WriteString(fmt.Sprintf("pub struct %s {\n", structName))
	for _, f := range fieldsForEvent(e.Name, v) {
		b.WriteString(fmt.Sprintf("    pub %s: %s,\n", f.Name, f.RustType))
	}
	b.WriteString("}\n")
	return b.String()
}

// snake converts CamelCase → snake_case.
func snake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + ('a' - 'A'))
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// structForVersion mirrors emit_go.swapVersionSuffix.
func structForVersion(e *events.RegistryEntry, v uint32) string {
	if len(e.Versions) > 1 && v != e.ActiveVersion {
		return swapVersionSuffix(e.GoStruct, v)
	}
	return e.GoStruct
}
