package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/loreweave/foundation/contracts/events"
)

// EmitGo writes the Go dispatch table at <outDir>/registry_generated.go.
//
// The generated file:
//   - is in `package events` (same package as hand-written structs)
//   - exposes `EventDispatch` map[string]map[uint32]string (type → version → struct name)
//   - exposes `LoadGeneratedRegistry()` that returns the registry parsed from
//     the embedded YAML — used by services that don't want to ship the YAML
//     separately
//
// Determinism: events sorted by name; version slice sorted ascending.
func EmitGo(reg *events.Registry, outDir string) error {
	var b strings.Builder
	b.WriteString("// Code generated by eventgen v" + version + ". DO NOT EDIT.\n")
	b.WriteString("// Source: contracts/events/_registry.yaml\n")
	b.WriteString("// Re-generate: make eventgen\n\n")
	b.WriteString("package events\n\n")
	b.WriteString("// EventDispatch maps (event_type, event_version) to the Go struct name in\n")
	b.WriteString("// contracts/events/. Consumers use this for runtime dispatch (logging, telemetry,\n")
	b.WriteString("// generic serialization paths).\n")
	b.WriteString("var EventDispatch = map[string]map[uint32]string{\n")

	for _, name := range reg.EventTypes() {
		e, _ := reg.LookupType(name)
		b.WriteString(fmt.Sprintf("\t%q: {\n", name))
		for _, v := range e.Versions {
			// Build the Go struct name from go_struct (active version's struct)
			// + the v-specific suffix when versions > 1. For single-version events
			// we just emit go_struct for all versions.
			structName := e.GoStruct
			if len(e.Versions) > 1 && v != e.ActiveVersion {
				// Heuristic: replace trailing Vn with V<v>
				structName = swapVersionSuffix(e.GoStruct, v)
			}
			b.WriteString(fmt.Sprintf("\t\t%d: %q,\n", v, structName))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")

	// Stable ordered slice of event types (handy for tests + iteration).
	b.WriteString("// EventTypesGenerated is the alphabetically-sorted list of event_type names\n")
	b.WriteString("// known to the registry at codegen time.\n")
	b.WriteString("var EventTypesGenerated = []string{\n")
	for _, n := range reg.EventTypes() {
		b.WriteString(fmt.Sprintf("\t%q,\n", n))
	}
	b.WriteString("}\n\n")

	// ── event-type NAME constants ────────────────────────────────────────────
	//
	// Added for T30/OD-1 (2026-08-12). Until then the generated output carried
	// payload types and a dispatch map but NO name surface in any language, so a
	// producer or consumer that wanted to name an event had no option but to write
	// its own string literal. `D-GLOSSARY-EVENTS-NO-SOT` recorded the result — one
	// const block in glossary-service, hand-mirrored by five consumers across four
	// services — and that was never a discipline failure by those five authors: it
	// was the only thing the contract made possible.
	//
	// Generating the names from the registry makes the registry the single owner,
	// which is what "the registry is authoritative" was always supposed to mean.
	b.WriteString("// Event-type name constants, generated from the registry.\n")
	b.WriteString("//\n")
	b.WriteString("// Import these instead of writing the literal. A rename in the registry\n")
	b.WriteString("// then becomes a COMPILE error at every use site — the property a string\n")
	b.WriteString("// literal can never give you, because the old spelling stays valid Go\n")
	b.WriteString("// forever and the handler simply stops running.\n")
	b.WriteString("const (\n")
	for _, n := range reg.EventTypes() {
		b.WriteString(fmt.Sprintf("\t%s = %q\n", goEventConstName(n), n))
	}
	b.WriteString(")\n")
	outPath := filepath.Join(outDir, "registry_generated.go")
	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}

// swapVersionSuffix turns "NpcSaidV2" + 1 → "NpcSaidV1". If no Vn suffix is
// present, append V<v>.
func swapVersionSuffix(base string, v uint32) string {
	// trim trailing digits
	i := len(base)
	for i > 0 && base[i-1] >= '0' && base[i-1] <= '9' {
		i--
	}
	// now check for trailing V
	if i > 0 && base[i-1] == 'V' {
		return fmt.Sprintf("%sV%d", base[:i-1], v)
	}
	return fmt.Sprintf("%sV%d", base, v)
}

// goEventConstName turns an event_type into an exported Go identifier:
// "glossary.entity_updated" -> "EventGlossaryEntityUpdated".
//
// Both `.` and `_` are word separators, so the two naming styles in the registry
// ("npc.said", "glossary.entity_updated") produce the same shape. The `Event`
// prefix is not decoration: without it "npc.said" would generate `NpcSaid`, which
// collides with nothing today but sits one event away from colliding with a
// payload struct name in the same package.
func goEventConstName(eventType string) string {
	var b strings.Builder
	b.WriteString("Event")
	for _, word := range strings.FieldsFunc(eventType, func(r rune) bool {
		return r == '.' || r == '_'
	}) {
		b.WriteString(strings.ToUpper(word[:1]))
		b.WriteString(word[1:])
	}
	return b.String()
}
