package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/loreweave/foundation/contracts/events"
)

// EmitPython writes Python type definitions to <outDir>/<event_snake>.py.
//
// Uses TypedDict (PEP 589) so the generated types work with Pydantic v2
// `TypeAdapter` and stay zero-runtime-overhead. Services that need true
// Pydantic models can wrap via `pydantic.create_model_from_typeddict`.
//
// Generates one __init__.py that re-exports all event types.
func EmitPython(reg *events.Registry, outDir string) error {
	var initLines []string
	var initExports []string
	for _, name := range reg.EventTypes() {
		e, _ := reg.LookupType(name)
		for _, v := range e.Versions {
			structName := structForVersion(e, v)
			fname := snake(structName) + ".py"
			content := renderPython(e, v, structName)
			if err := os.WriteFile(filepath.Join(outDir, fname), []byte(content), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", fname, err)
			}
			modName := snake(structName)
			initLines = append(initLines, fmt.Sprintf("from .%s import %s", modName, structName))
			initExports = append(initExports, fmt.Sprintf("    %q,", structName))
		}
	}
	// __init__.py
	var ib strings.Builder
	ib.WriteString("# Code generated by eventgen v" + version + ". DO NOT EDIT.\n")
	ib.WriteString("# Re-generate: make eventgen\n\n")
	for _, l := range initLines {
		ib.WriteString(l + "\n")
	}
	ib.WriteString("\n__all__ = [\n")
	for _, l := range initExports {
		ib.WriteString(l + "\n")
	}
	ib.WriteString("]\n")
	return os.WriteFile(filepath.Join(outDir, "__init__.py"), []byte(ib.String()), 0o644)
}

func renderPython(e *events.RegistryEntry, v uint32, structName string) string {
	var b strings.Builder
	b.WriteString("# Code generated by eventgen v" + version + ". DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("# Event: %s v%d\n", e.Name, v))
	b.WriteString(fmt.Sprintf("# %s\n\n", e.Description))
	// Imports: we only import what fields actually need.
	imports := pythonImports(fieldsForEvent(e.Name, v))
	for _, imp := range imports {
		b.WriteString(imp + "\n")
	}
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	b.WriteString("from typing import TypedDict\n\n\n")
	b.WriteString(fmt.Sprintf("class %s(TypedDict):\n", structName))
	b.WriteString(fmt.Sprintf("    \"\"\"%s\"\"\"\n", e.Description))
	for _, f := range fieldsForEvent(e.Name, v) {
		b.WriteString(fmt.Sprintf("    %s: %s\n", f.Name, f.PythonType))
	}
	return b.String()
}

// pythonImports returns the `from X import Y` lines needed for the field set.
func pythonImports(fields []Field) []string {
	needsDatetime := false
	for _, f := range fields {
		if f.PythonType == "datetime" {
			needsDatetime = true
		}
	}
	var out []string
	if needsDatetime {
		out = append(out, "from datetime import datetime")
	}
	return out
}

// (snake() is defined in emit_rust.go and shared across emitters.)
