package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/loreweave/foundation/contracts/events"
)

// EmitSDKPythonConstants writes a SELF-CONTAINED Python module of event-name constants
// to path, for distribution through `sdks/python` (T30 / OD-1, 2026-08-12).
//
// WHY THIS EXISTS SEPARATELY FROM EmitPython
// ------------------------------------------
// `EmitPython` already writes payload TypedDicts and a barrel under
// `contracts/events/generated/python/`, and that tree is real, correct — and imported by
// nothing. `scripts/eventgen-validate.sh` says so in its own header: *"Nothing consumes the
// Rust/TS/Python bindings YET."* The reason is not neglect: that directory is not on any
// Python service's import path and is not packaged, so a consumer COULD not import it.
//
// Meanwhile the three Python consumers of `glossary.*` each hand-declared the event names
// they dispatch on — the exact `D-GLOSSARY-EVENTS-NO-SOT` disease the Go side has just been
// cured of. Curing only the Go half would have been worse than leaving it alone: the
// surviving copies would be in a different language from the owner, so no compiler, linker
// or grep relates them any more.
//
// So this emits ONE dependency-free module into the shared SDK, which every Python service
// already installs. It carries names only, not payload types: consumers dispatch on the
// name and parse the body as a dict, and shipping the TypedDicts here would duplicate the
// generated tree rather than replace it.
//
// SELF-CONTAINED IS DELIBERATE. It imports nothing — not even from
// `contracts/events/generated/python` — because the SDK is installed into service images
// that do not contain the contracts tree. A re-export shim would import cleanly on a
// developer's checkout and fail at container start, which is the worst possible place for
// this particular class of bug to appear.
func EmitSDKPythonConstants(reg *events.Registry, path string) error {
	var b strings.Builder
	b.WriteString("# Code generated by eventgen v" + version + ". DO NOT EDIT.\n")
	b.WriteString("# Source: contracts/events/_registry.yaml\n")
	b.WriteString("# Re-generate: make eventgen\n")
	b.WriteString(`"""Event-type name constants — the Python half of the event-name contract.

Import these instead of writing the literal::

    from loreweave_events import EVENT_GLOSSARY_ENTITY_UPDATED

    dispatcher.register(EVENT_GLOSSARY_ENTITY_UPDATED, handle_entity_updated)

WHY THIS MATTERS MORE IN PYTHON THAN IN GO
------------------------------------------
Go gives you a compile error when a constant disappears. Python gives you an ImportError at
STARTUP — which is still enormously better than the alternative this replaces. A
hand-written string literal for an event that no longer exists is valid Python forever: the
dispatcher registers a handler under a name nothing emits, every test that mocks the
dispatcher still passes, and the only symptom is that the handler silently never runs.

That is not hypothetical here. It is recorded as D-GLOSSARY-EVENTS-NO-SOT: seven event
names owned by glossary-service and hand-mirrored by five consumers across four services,
with nothing relating the copies.
"""
`)
	b.WriteString("\n")

	var names []string
	for _, n := range reg.EventTypes() {
		names = append(names, pyEventConstName(n))
		b.WriteString(fmt.Sprintf("%s = %q\n", pyEventConstName(n), n))
	}

	// __all__ so `from loreweave_events import *` and static analysers agree with the
	// module's actual surface. Generated rather than hand-listed for the same reason
	// everything else here is.
	b.WriteString("\n__all__ = [\n")
	for _, n := range names {
		b.WriteString(fmt.Sprintf("    %q,\n", n))
	}
	b.WriteString("]\n")

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
