package main

import (
	"flag"
	"fmt"
	"log"
	"os"
)

// version is the eventgen tool version. Bump on changes that alter the
// generated-output byte-shape so consumers can grep for the embedded marker
// in `// Code generated by eventgen v<X.Y.Z>. DO NOT EDIT.`
const version = "0.1.0"

func main() {
	var (
		registryPath = flag.String("registry", "contracts/events/_registry.yaml", "path to _registry.yaml")
		eventsDir    = flag.String("events-dir", "contracts/events", "path to annotated event struct files")
		outDir       = flag.String("out-dir", "contracts/events/generated", "output root for generated files")
		target       = flag.String("target", "all", "codegen target: all | go | rust | ts | python")
		scope        = flag.String("scope", "events", "codegen scope: events | contracts (contracts reserved for Q-L4-3 V2)")
		validate     = flag.Bool("validate", false, "validate-only: parse registry + abort without writing files")
		showVersion  = flag.Bool("version", false, "print version and exit")
	)
	flag.Parse()

	if *showVersion {
		fmt.Printf("eventgen %s\n", version)
		return
	}

	if *scope == "contracts" {
		log.Fatalf("--scope=contracts reserved for Q-L4-3 V2+ (contractgen); V1 only supports --scope=events")
	}
	if *scope != "events" {
		log.Fatalf("unknown --scope %q (want: events)", *scope)
	}

	cfg := Config{
		RegistryPath: *registryPath,
		EventsDir:    *eventsDir,
		OutDir:       *outDir,
		Target:       *target,
		Validate:     *validate,
	}
	if err := Run(cfg); err != nil {
		log.Fatalf("eventgen: %v", err)
	}
	if !*validate {
		fmt.Fprintf(os.Stderr, "eventgen: %s codegen complete (out=%s)\n", *target, *outDir)
	}
}
