"""Lane LB — golden-set / backward-compat proof for dynamic extraction schema.

KG customizable-ontology epic (docs/specs/2026-06-20-...): the extraction SDK
ontology (entity/event/fact kinds + edge predicates) moves from a hardcoded
``Literal`` + ``.md`` vocab to a schema PASSED IN at call time. This is the
HIGHEST-RISK lane: the SDK is consumed by knowledge-service, worker-ai, AND
translation-service. The NON-NEGOTIABLE rule: ``schema=None`` reproduces today's
EXACT static behavior (byte-identical prompt + same Literal validation) so the
other two services are byte-for-byte unaffected.

This file proves backward-compat DETERMINISTICALLY (no LLM calls):

  1. Snapshot test — schema=None prompt == the pre-change static prompt
     (hashes captured from the pre-LB code; this test FAILS if the default
     path is altered).
  2. Validation parity — schema=None accepted kind/type sets == today's
     Literal members exactly.
  3. Dynamic path — schema=<xianxia-harem> injects the schema's
     edges/drives/kinds into the prompt + validation accepts them + rejects
     off-schema values fail-soft (collect via on_dropped, never crash).
"""

from __future__ import annotations

import hashlib

import pytest

from loreweave_extraction.extractors import entity, event, fact, relation
from loreweave_extraction.extractors.entity import (
    _STATIC_ENTITY_KINDS,
    _tolerant_parse_entities,
)
from loreweave_extraction.extractors.event import (
    _STATIC_EVENT_KINDS,
    _tolerant_parse_events,
)
from loreweave_extraction.extractors.fact import (
    _STATIC_FACT_TYPES,
    _tolerant_parse_facts,
)
from loreweave_extraction.extractors.relation import _postprocess as _rel_postprocess
from loreweave_extraction.schema_projection import (
    DEFAULT_VOCAB_SOFT_CAP,
    ExtractionSchema,
)

# ── Baseline hashes captured from the PRE-LB static builders ──────────
# Generated by running the pre-change `build_<op>_system(["Kai","Harbin"])`
# on the parent branch and hashing the result. If the schema=None default
# path ever drifts byte-for-byte, these hashes mismatch → test FAILS, which
# is exactly the backward-compat tripwire worker-ai + translation rely on.
_KNOWN = ["Kai", "Harbin"]
_BASELINE_SHA256 = {
    "entity": "b4df60706db908ad5a1ea6564818e04c5e6ec63b186cdae3d10973d48878e954",
    "relation": "942544041a4c82b12d28aaa673ccbb762046d8c984e7e4c45df655fc4aed6e73",
    "event": "56a475dff1ab7cf7ea19e247265dc6319a50dfc957b24b289409d1061286fc02",
    "fact": "900a52ba19238f42332d3a8652888d638d6f466ddc93fbc732ff546ff67b9fd0",
}

_BUILDERS = {
    "entity": entity.build_entity_system,
    "relation": relation.build_relation_system,
    "event": event.build_event_system,
    "fact": fact.build_fact_system,
}


def _sha(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


# ── (1) snapshot: schema=None is byte-identical to the static .md prompt ──


@pytest.mark.parametrize("op", ["entity", "relation", "event", "fact"])
def test_schema_none_prompt_byte_identical_to_static(op):
    built = _BUILDERS[op](_KNOWN)  # schema defaults to None
    assert _sha(built) == _BASELINE_SHA256[op], (
        f"{op}: schema=None prompt drifted from the pre-LB static .md prompt — "
        "backward-compat BROKEN (worker-ai + translation get different output)"
    )


@pytest.mark.parametrize("op", ["entity", "relation", "event", "fact"])
def test_schema_none_explicit_equals_default(op):
    """Passing schema=None explicitly == the no-schema default (no path split)."""
    assert _BUILDERS[op](_KNOWN) == _BUILDERS[op](_KNOWN, schema=None)


@pytest.mark.parametrize("op", ["entity", "relation", "event", "fact"])
def test_empty_schema_appends_nothing(op):
    """A degenerate schema (no projected vocab for the op) appends NOTHING —
    still byte-identical to the static prompt (the dynamic block only renders
    when there's vocab)."""
    empty = ExtractionSchema()  # all vocab tuples empty
    assert _sha(_BUILDERS[op](_KNOWN, schema=empty)) == _BASELINE_SHA256[op]


# ── (2) validation parity: schema=None accepts exactly today's Literal set ──


def _job_items(items):
    """Minimal stand-in: the tolerant parsers take the raw list directly."""
    return items


def test_entity_validation_parity_static():
    # Every static kind accepted; an off-Literal kind dropped (schema=None).
    dropped = []
    items = [{"name": "X", "kind": k, "confidence": 0.9} for k in _STATIC_ENTITY_KINDS]
    items.append({"name": "Y", "kind": "cultivator", "confidence": 0.9})  # off-Literal
    out = _tolerant_parse_entities(items, on_dropped=lambda op, r: dropped.append(r))
    accepted_kinds = {e.kind for e in out}
    assert accepted_kinds == _STATIC_ENTITY_KINDS
    assert dropped == ["validation"]  # the cultivator dropped


def test_event_validation_parity_static():
    dropped = []
    items = [
        {"name": "e", "kind": k, "summary": "s", "participants": ["Kai"], "confidence": 0.9}
        for k in _STATIC_EVENT_KINDS
    ]
    items.append({"name": "e", "kind": "breakthrough", "summary": "s",
                  "participants": ["Kai"], "confidence": 0.9})
    out = _tolerant_parse_events(items, on_dropped=lambda op, r: dropped.append(r))
    assert {e.kind for e in out} == _STATIC_EVENT_KINDS
    assert dropped == ["validation"]


def test_fact_validation_parity_static():
    dropped = []
    items = [{"content": "c", "type": t, "confidence": 0.9} for t in _STATIC_FACT_TYPES]
    items.append({"content": "c", "type": "realm", "confidence": 0.9})
    out = _tolerant_parse_facts(items, on_dropped=lambda op, r: dropped.append(r))
    assert {f.type for f in out} == _STATIC_FACT_TYPES
    assert dropped == ["validation"]


# ── (3) dynamic path: xianxia-harem schema ─────────────────────────────

XIANXIA_HAREM = ExtractionSchema(
    entity_kinds=("person", "cultivator", "sect", "spirit_beast", "dao_companion"),
    edge_predicates=("pursues", "disciple_of", "dao_companion_of", "rival_of", "seeks"),
    event_kinds=("action", "breakthrough", "tribulation", "courtship"),
    fact_types=("description", "realm", "affection"),
    allow_free_edges=False,  # CLOSED edge set
    label="xianxia-harem@v1",
)


@pytest.mark.parametrize("op,needles", [
    ("entity", ["cultivator", "dao_companion"]),
    ("relation", ["pursues", "dao_companion_of"]),
    ("event", ["breakthrough", "tribulation"]),
    ("fact", ["realm", "affection"]),
])
def test_dynamic_prompt_injects_schema_vocab(op, needles):
    built = _BUILDERS[op](_KNOWN, schema=XIANXIA_HAREM)
    assert "Project ontology (custom schema)" in built
    for n in needles:
        assert n in built, f"{op}: schema vocab {n!r} not injected into prompt"
    # Still byte-DIFFERENT from the static prompt (the dynamic block was added).
    assert _sha(built) != _BASELINE_SHA256[op]


def test_dynamic_relation_closed_set_note_present():
    built = relation.build_relation_system(_KNOWN, schema=XIANXIA_HAREM)
    assert "CLOSED" in built  # allow_free_edges=False states the closed rule


def test_dynamic_relation_free_edges_note_when_open():
    open_schema = ExtractionSchema(
        edge_predicates=("pursues", "seeks"), allow_free_edges=True,
    )
    built = relation.build_relation_system(_KNOWN, schema=open_schema)
    assert "may coin" in built.lower()
    assert "CLOSED" not in built


def test_dynamic_entity_validation_accepts_schema_kind():
    dropped = []
    items = [
        {"name": "Mc", "kind": "cultivator", "confidence": 0.9},   # in schema, off static
        {"name": "Sect", "kind": "sect", "confidence": 0.9},       # in schema, off static
        {"name": "Bad", "kind": "spaceship", "confidence": 0.9},   # off schema → drop
    ]
    out = _tolerant_parse_entities(
        items, on_dropped=lambda op, r: dropped.append(r), schema=XIANXIA_HAREM,
    )
    kinds = {e.kind for e in out}
    assert kinds == {"cultivator", "sect"}
    assert dropped == ["validation"]  # only the spaceship dropped


def test_dynamic_event_validation_accepts_schema_kind():
    dropped = []
    items = [
        {"name": "e", "kind": "breakthrough", "summary": "s",
         "participants": ["Kai"], "confidence": 0.9},
        {"name": "e2", "kind": "warp_jump", "summary": "s",
         "participants": ["Kai"], "confidence": 0.9},
    ]
    out = _tolerant_parse_events(
        items, on_dropped=lambda op, r: dropped.append(r), schema=XIANXIA_HAREM,
    )
    assert {e.kind for e in out} == {"breakthrough"}
    assert dropped == ["validation"]


def test_dynamic_fact_validation_accepts_schema_type():
    dropped = []
    items = [
        {"content": "Mc is at Foundation Establishment", "type": "realm", "confidence": 0.9},
        {"content": "x", "type": "stock_price", "confidence": 0.9},
    ]
    out = _tolerant_parse_facts(
        items, on_dropped=lambda op, r: dropped.append(r), schema=XIANXIA_HAREM,
    )
    assert {f.type for f in out} == {"realm"}
    assert dropped == ["validation"]


def test_dynamic_closed_edge_set_drops_off_vocab_predicate():
    """Relation _postprocess drops an off-vocab predicate fail-soft when the
    edge set is CLOSED, reporting via on_dropped — never crashes."""
    from loreweave_extraction.extractors.relation import _LLMRelation

    dropped = []
    raws = [
        _LLMRelation(subject="Mc", predicate="pursues", object="Dao", confidence=0.9),
        _LLMRelation(subject="Mc", predicate="hacks", object="Server", confidence=0.9),
    ]
    out = _rel_postprocess(
        raws, entities=[], known_entities=[], user_id="u", project_id=None,
        schema=XIANXIA_HAREM, on_dropped=lambda op, r: dropped.append(r),
    )
    preds = {r.predicate for r in out}
    assert "pursues" in preds
    assert "hacks" not in preds
    assert dropped == ["off_schema_edge"]


def test_open_edge_set_keeps_off_vocab_predicate():
    """allow_free_edges=True → off-vocab predicates survive (today's behavior)."""
    from loreweave_extraction.extractors.relation import _LLMRelation

    open_schema = ExtractionSchema(
        edge_predicates=("pursues",), allow_free_edges=True,
    )
    raws = [_LLMRelation(subject="Mc", predicate="hacks", object="Server", confidence=0.9)]
    out = _rel_postprocess(
        raws, entities=[], known_entities=[], user_id="u", project_id=None,
        schema=open_schema,
    )
    assert {r.predicate for r in out} == {"hacks"}


# ── (b1) §10-B1 token-budget soft cap + log on truncate ────────────────


def test_vocab_soft_cap_truncates_prompt_but_not_validation(caplog):
    import logging

    big = tuple(f"kind_{i}" for i in range(DEFAULT_VOCAB_SOFT_CAP + 10))
    schema = ExtractionSchema(entity_kinds=big, vocab_soft_cap=DEFAULT_VOCAB_SOFT_CAP,
                              label="big@v1")
    with caplog.at_level(logging.WARNING):
        rendered = schema.render_entity_kinds()
    assert len(rendered) == DEFAULT_VOCAB_SOFT_CAP  # prompt hint trimmed
    assert any("truncated" in r.message for r in caplog.records)  # logged
    # Validation still accepts a value BEYOND the cap (truncation = prompt only).
    dropped = []
    over_cap_kind = big[-1]  # past the soft cap
    out = _tolerant_parse_entities(
        [{"name": "Z", "kind": over_cap_kind, "confidence": 0.9}],
        on_dropped=lambda op, r: dropped.append(r), schema=schema,
    )
    assert [e.kind for e in out] == [over_cap_kind]
    assert dropped == []


def test_from_resolved_builds_projection_and_degrades_gracefully():
    resolved = {
        "entity_kinds": ["person", "cultivator", "person", "  ", 5],  # dedup + drop junk
        "edge_predicates": ["pursues"],
        "allow_free_edges": False,
        "label": "proj-1@v3",
    }
    sch = ExtractionSchema.from_resolved(resolved)
    assert sch.entity_kinds == ("person", "cultivator")  # deduped, junk dropped
    assert sch.edge_predicates == ("pursues",)
    assert sch.allow_free_edges is False
    assert sch.label == "proj-1@v3"
    # Missing keys → empty (more permissive, never stricter).
    assert sch.event_kinds == ()
    assert sch.fact_types == ()
